### ISSUE TITLE
Detect word length also for chinese text

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#105]
Chinese literary language has no blanks/spaces in front of or after the punctuation marks. That leads to the situation that **a whole paragraph** with chinese characters **counts as one word**, when checking the word length (see [functions.inc.php, line 1209](https://github.com/ilosuna/mylittleforum/blob/master/includes/functions.inc.php#L1209) (at the moment)).

Two suggestions from me.

- The value of `0` for the setting could disable the check. There are similar checks, that should be handled in the same manner.
- Introduce a language dependent key-value-pair in the language file(s), that declares the characters, that separate words. Maybe this should be optional. Then it would only be used in the case, when the character is not the space/blank.

I for myself prefer the second approach.

**Comment by derletztekick** [comment]
The function too_long_word is uses to check the length of the strings. So I add a condition, see https://github.com/ilosuna/mylittleforum/pull/109

Done.

**Comment by auge8472** [comment]
Thank you for the disable-the-check code. However, I think, it should be also possible to check the word length in languages, where a whole paragraph is a string without spaces (like in chinese language). Therefor we should consider a more complex solution as addition to the disabling. Thatswhy I will reopen the issue. No offense!

**Comment by auge8472** [comment]
So a chinese forum admin can choose between `text_word_maxlength = 0` to disable the check and `text_word_maxlength` with a very high value of `X`, that breaks in the moment, when someone want to post a longer paragraph then the setting allows?

That's *IMHO* not satisfying.

**Comment by derletztekick** [comment]
Hi,

yes, you are right. You suggest a version linke `too_long_word($text,$word_maxlength,$delimiters)` like my suggestion in https://github.com/ilosuna/mylittleforum/pull/110? Now, you can add characters to the function to split the text.

**Comment by derletztekick** [comment]
I add a new item to lang file called 'word_delimiters'. A list of *single* characters can add to this list e.g. `word_delimiters = ，。；“”！` for Chinese. A regular expression will replace this chars, i.e. `$text = preg_replace("/[".preg_quote($delimiters, '/')."]/", " ", $text);` to estimate the _word_ lengths.
Does this modification fulfils your suggestions?

**Comment by derletztekick** [comment]
Sorry for closing. I clicked the wrong button.

**Comment by auge8472** [comment]
> Does this modification fulfils your suggestions?

Souds, that it does. Will read the code later.
