### ISSUE TITLE
Table for temporary informations

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#123]
The information about the actual installable release will be loaded from the [latest release page of the repository](https://github.com/ilosuna/mylittleforum/releases/latest). In a first step the request for the info fires on every request of the main page of the admin area and the landing page (overview of the threads), if the user is an admin. See #44 for the details.

We want to limit the number of requests for the new version (to two, three or four times a day). Thatswhy we need a temporary storage for the infos about the last request and the found value. At that point it is appropriate to consider the transfer of a few settings (which are no "settings" at all) to the new table in a second step.

**Comment by derletztekick** [comment]
The update-check is only called, if an admin visits the main page of the _admin area_ but not by visiting the normal main page (thread overview). So, if the admin not visits the admin area, no request will done. This reduced the traffic much more than to request github several times each day.

> We want to limit the number of requests for the new version (to two, three or four times a day).

You can add it to the given function [daily_actions()](https://github.com/ilosuna/mylittleforum/blob/master/includes/functions.inc.php#L83)

**Comment by auge8472** [comment]
> The update-check is only called, if an admin visits the main page of the admin area but not by visiting the normal main page (thread overview).

Yes, meanwhile I saw this. :-)

> > We want to limit the number of requests for the new version (to two, three or four times a day).
> 
> You can add it to the given function daily_actions()

Seems to be more reasonable.

**Comment by derletztekick** [comment]
> Seems to be more reasonable.

That is the question. In the prior version no request was done, if the admin didn't the admin area.

**Comment by auge8472** [comment]
> In the prior version no request was done, if the admin didn't visited the admin area.

Ok, no request for the admin area, no request for the feed. That saves bandwidth but on the other hand, the once-a-day-request in the context of the function `daily_actions` seems to be no problem for me.
