### ISSUE TITLE
Entries could be marked as new and as read

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#128]
With the new behaviour of the read-marking (see #45 ff.) it is possible to mark an entry as read while the entry is also marked as new. There are two if-blocks in the templates, one for the new-marking and another one for the read-marking. It should be an if-else-block, that marks an entry as read if the user is logged in and the entry **is** read and otherwise mark the entry as new, if the entry is newer than the last visit.

**Comment by derletztekick** [comment]
It is not a elseif itself. A suggestion may

```
{if $data.$element.pid==0 && $data.$element.new && !$data.$element.is_read}
	{if $data.$element.sticky==1 && $data.$element.locked==1}
		threadnew-sticky-locked
	{elseif $data.$element.sticky==1}
		threadnew-sticky
	{elseif $data.$element.locked==1}
		threadnew-locked{else}threadnew
	{/if}
{elseif $data.$element.pid==0}
	{if $data.$element.sticky==1 && $data.$element.locked==1}
		thread-sticky-locked
	{elseif $data.$element.sticky==1}
		thread-sticky
	{elseif $data.$element.locked==1}
		thread-locked
	{else}
		thread
	{/if}
	{if $data.$element.is_read}
		 read
	{/if}
{elseif $data.$element.pid!=0 && $data.$element.new && !$data.$element.is_read}
	replynew
{else}
	reply
	{if $data.$element.is_read}
		 read
	{/if}
{/if}
```

**Comment by auge8472** [comment]
Because of the confusing set of combinations of "new", "sticky" **or** "locked" and all these again with **and** in a two-item- and a three-item-combination, I think this system reaches its limit. The next iteration with a new, additional state will make our (developers) heads explode.

The "read" state has fortunately only one counterpart, the "new" state. An entry can be sticky, it can be closed or not, but it is independent from that read or unread. The only additional complexity is the necessity of distinction between a registered vs. an unregistered visitor.

For only a registered visitor the decision is easy, the entry is read (`!== new`) or it is not (`=== new`). The information from the cookie about the last visit or login is unnecessary in this case.

An unregistered user on the other hand has no stored read state for the entries. So we need the info from the cookie furthermore or (maybe) we (can) work with the sub classes `:link` and `:visited` instead, to simplify the code. If the user read the entry in the nearer past, the browser will use the CSS-rules for `a:visited` without any action undertaken by a script, otherwise the rules for `a:link` will be in use.

With a more complex CSS-selector `ul.thread li.thread a:link:not(:read) {}` and `ul.thread li.thread a:visited:not(:read) {}` we can take away complexitiy from other places (PHP, Smarty). I will try this, but *for now* I have to say, I don't know, if it's a good idea.

The browser support [is good enough](http://caniuse.com/#feat=css-sel3) and the less of complexity in the PHP- and Smarty-code is welcome (IMHO) but on the other hand it makes the CSS-code more feature rich *but also and for this reason* less readable for "non-profis".

**Comment by derletztekick** [comment]
Well, the problem is the behaviour of `$data.$element.new` and `$data.$element.is_read`. Maybe, it is easier to handle this issue on php site, e.g. if is_read is true then new must be false.

**Comment by derletztekick** [comment]
Isn't it a possible solution to modify your code part:

```
     if ($data['req_user'] !== NULL and is_numeric($data['req_user'])) {
       $data['is_read'] = true;
     } else {
       $data['is_read'] = false;
     }
```

to

```
     if ($data['req_user'] !== NULL and is_numeric($data['req_user'])) {
       $data['is_read'] = true;
       $data['new'] = false;
     } else {
       $data['is_read'] = false;
     }
```

?

**Comment by auge8472** [comment]
Yes, it seems to be a proper solution. At least it's going into the correct direction.

My own thinking presumes to often the state of a registered user, where I have only to decide between *A* and *B*. But the forum has the ability to take part as an unregistered visitor and that needs a *C*.

**Comment by derletztekick** [comment]
Should I add this line or do you want to edit the file?

**Comment by auge8472** [comment]
I want to edit the file. But before I'll do it, I want to sort my thoughts.

The query reads the read status from the read-status-table inside a left join (leftg hand the entry, right hand the status table). The result contains `TRUE` when an registrered and logged in user reads the entry data **and** the user has read the entry before. Otherwise (in every different case) the result will be `FALSE`.

The `TRUE`-case is self-explanatory. So we have to distinguish between logged in and unregistered user only in the case `FALSE`. At that point we have an user-ID or we haven't. Is there a user-ID, the entry is unread and should be marked as "new" (ticked).

Otherwise we see the request of an unregistered user. At that point we decide the new status (a read status doesn't exist in this case) on the basis of the cookie like usual until now.

Did I miss  something?

**Comment by derletztekick** [comment]
> Did I miss something?

Sounds valid.
