### ISSUE TITLE
Smarty parse error with disabled count_views

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#132]
When `count_views` is disabled, an error occurs in `main.inc.php`, [line 254](https://github.com/ilosuna/mylittleforum/blob/master/includes/index.inc.php#L254), when Smarty tries to assign the value of the counted views for the current processed entry from the array `$total_views`.

**Comment by derletztekick** [comment]
Done: https://github.com/ilosuna/mylittleforum/pull/133
