### ISSUE TITLE
Link of the release info targets "latest"

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#155]
When a pre release is the latest/newest release, the info text will be shown correct and the link goes to "releases/latest". But under "releases/latest" one will find the latest *stable* release instead the in the message named pre release. Thats not a problem because one can click the "releases" link on the page "releases/latest", but it would be much better and an improvement for the usability if the link leads to the release page itself.

The info about the direct link to the release is in the Atom-feed available under `<feed><entry><link rel="alternate" type="text/html" href="/direct/link/to/the/release"/>` and could be stored in an additional row in the database entry.

**Comment by derletztekick** [comment]
Done.
