### ISSUE TITLE
database error in bookmark table

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#159]
This is a bug report from @ilosuna 

When adding a bookmark, an error occurs with the following error message

~~~
Database error! Column 'order_id' cannot be null.
~~~

PHP 7.0.8, MySQL 5.7.17

**Comment by derletztekick** [comment]
Seems to be a problem in https://github.com/ilosuna/mylittleforum/blob/master/includes/posting.inc.php#L304

Please try:

`SELECT COALESCE(MAX( `order_id` ), 0) + 1`

in SQL

**Comment by derletztekick** [comment]
I cannot reproduce this issue because the order_id has a default value. Thus, Null is never set. Anyway, I surround the sql-statement by COALESCE to check for Null-values. see https://github.com/ilosuna/mylittleforum/pull/160

Please close this issue, if you have check the new code.

**Comment by auge8472** [comment]
Seems to be ok. The table create statement says `order_id int(11) NOT NULL DEFAULT '0'`. There is, as you stated, a default value that is not `NULL` **and** `NULL` itself as value is "*forbidden*". So a case, where a `NULL` could be stored to the field *should **never** occure* because the default value of `0` would come into game.

It would be helpful, if @ilosuna shows the table definition for the bookmarks table, as it is returned by *his* MySQL server.
