### ISSUE TITLE
Set classes instead inline styles

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#16]
There are some places in the JavaScript-code with manipulations of HTML-elements. In many cases these manipulations are done by setting inline styles. It would be better to set or unset classes and manipulate the styles in the always existing CSS-ressource(s). It would also lead to a simpler theming.

**Comment by derletztekick** [comment]
Okay, I think this is my part. I will start to _clean_ up the JS-code

**Comment by derletztekick** [comment]
Done.

**Comment by auge8472** [comment]
I hope, that we can keep the commits for version 2.4 apart from the bugfixes for 2.3.7. Having said that thank you for your work.
