### ISSUE TITLE
no info about actualised language files when updating from 2.3.99.1 to 2.4.1?

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#176]
I updated a test installation which was installed on december the 2nd 2016. This was one and a half months before the [first public beta 2.3.99.2](https://github.com/ilosuna/mylittleforum/releases/tag/v2.3.99.2). But even the 2.3.99.3 brought changes in the lang files and these [were noted in the update script](https://github.com/ilosuna/mylittleforum/blob/v2.4/update/update_2.3.5-2.4.php#L81), the update script doesn't mention me to copy the files of the directory `lang/` to the server.

Is there anyone outside, who noticed the same or a similar behaviour?

**Comment by derletztekick** [comment]
Hi,

I updated from 2.3.7 to 2.4 (and later to 2.4.1) and the lang-directory was shown in the list. Thus, I cannot confirm your issue. You can copy the lines 22-134 to a single file and check the resulting `$update` array. Is  lang-directory excluded?

/Micha

**Comment by auge8472** [comment]
I noticed, that the box for the current version number was emty and the no-gender-specified button (see #157) was present but not labeled. That led me to copy the lang dir and afterwards the error was solved.

It might absolutely be possible, that I missed the entry in the list of files to update. The list was unordered, so a file from directory `includes/` was followed by an entry from the theme, which itself was follwed by an entry from `includes/`. I am afterwards **absolutely not sure**, what I saw and what not. *Thatswhy* the issue is labeled as "question" and not as "bug". :-)

**Comment by auge8472** [comment]
> You can copy the lines 22-134 to a single file and check the resulting $update array. Is lang-directory excluded?

No, up to old/source version 2.3.99.2 the directory `lang/` is listed. That's, what the code determines. I'll close the issue.
