### ISSUE TITLE
better sorting of the list of updateeable files and directories

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#177]
As noted in #176 the ordering of the list of updateable files and directories is IMHO not satisfying. The list will be combined with the block of files first, followed by the block of folders. But the blocks in itself are not ordered. So a file from directory A is followed by a file from directory B and this is followed again by a file from directory A.

Because this can be confusing I propose an alphabetically ordering of every single block before combining the blocks to one array.

**Comment by derletztekick** [comment]
Good point!

**Comment by derletztekick** [comment]
Done by https://github.com/ilosuna/mylittleforum/pull/178
