### ISSUE TITLE
spinning wheel shown permanently

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#187]
Not logged in visitors see the spinning wheel permanently on the posting page.

[reported by the user magma in the project forum](http://mylittleforum.net/forum/index.php?id=9917)

**Comment by derletztekick** [comment]
I cannot confirm this behaviour. The link to mlf is broken. Do you delete this posting?

**Comment by auge8472** [comment]
I only saw the screenshot in magmas posting. It seems, he/she deleted it.

**Comment by derletztekick** [comment]
> I only saw the screenshot in magmas posting
I believe, it is a caching issue because of the Inline-Style (CSS/JavaScript) changes.

> It seems, he/she deleted it.
One can delete its own postings???

**Comment by auge8472** [comment]
> > I only saw the screenshot in magmas posting

> I believe, it is a caching issue because of the Inline-Style (CSS/JavaScript) changes.

It's also possible, that he ran into the testing-with-disabled-JavaScript-trap.

> > It seems, he/she deleted it.

> One can delete its own postings???

I didn't, and it seems so you. But the entry is gone.

I didn't, and it seems neither you. But the entry is gone.

**Comment by derletztekick** [comment]
> It's also possible, that he ran into the testing-with-disabled-JavaScript-trap.

No, because this icon ("throbber.gif") is added to the DOM by JavaScript, cf. https://github.com/ilosuna/mylittleforum/blob/master/js/main.js#L1070

**Comment by auge8472** [comment]
Why is the image then hardcoded in the template?

**Comment by derletztekick** [comment]
My fault! The code in JavaScript is used to show the AjaxPreviewWindow.

In the template file, the image has the class js-visibility-hidden, which means, the the image is set to [visibility:hidden; ](https://github.com/ilosuna/mylittleforum/blob/master/themes/default/style.css#L669) by the css rule. Thus, the image is never shown, if JavaScript is not available.
