### ISSUE TITLE
wrong browser cache handling in IE

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#188]
The statement in [index.php, line 209](https://github.com/ilosuna/mylittleforum/blob/master/index.php#L209) does not detect the MS Internet Explorer because of the not in the user agent string found search string "MSIE".

On the other hand [the distinction between IE and the others](https://github.com/ilosuna/mylittleforum/blob/master/index.php#L213) seems to be unnecessary. Setting the HTTP-header `'Cache-Control: private, no-cache="set-cookie"'`, like suggested [in this forum entry](http://mylittleforum.net/forum/index.php?id=9925), seems to work in all browsers (actually untested).

**Comment by derletztekick** [comment]
> seems to work in all browsers
Okay, just change it.

**Comment by auge8472** [comment]
> > seems to work in all browsers

> Okay, just change it.

Please bear in mind the parenthesised part "actually untested". I think, we should perform further tests for possible side effects in other browsers.

**Comment by auge8472** [comment]
fixed with #207
