### ISSUE TITLE
make time limit for login blocking configurable

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#19]
An IP can be blocked, when three login attempts in a row from this IP failed. The time limit (at the moment 10 minutes) is hardcoded. It should be configurable as a forum setting.

Question and solution is available [here and in the following entries](http://mylittleforum.net/forum/index.php?id=9197).

**Comment by derletztekick** [comment]
Hey Auge,

why not use the existing table value, i.e. a zero value means 'off' and a value greater than zero is interpreted as time in minutes. Thus, we don't have to add a new value in the database:

```DELETE FROM `mlf2_logincontrol` WHERE time < (NOW()-INTERVAL (SELECT CONVERT(`value`,UNSIGNED INTEGER) FROM `mlf2_settings` WHERE `name` = 'temp_block_ip_after_repeated_failed_logins') MINUTE)```

in login.inc.php line 37ff:
```
// clear failed logins and check if there are failed logins from this ip:
// a value greater than zero is interpreted as time in minutes.
if($settings['temp_block_ip_after_repeated_failed_logins'] > 0)
 {
  @mysqli_query($connid, "DELETE FROM ".$db_settings['login_control_table']." WHERE time < (NOW()-INTERVAL (SELECT CONVERT(`value`,UNSIGNED INTEGER) FROM ".$db_settings['settings_table']." WHERE `name` = 'temp_block_ip_after_repeated_failed_logins') MINUTE)");
...
```

And an update within the next version:
```UPDATE ".$db_settings['settings_table']." SET `value`=10 WHERE `name` = 'temp_block_ip_after_repeated_failed_logins' AND `value` > 0```

/Micha

**Comment by auge8472** [comment]
Ah, I didn't now this setting. Rhetorical question: Why it wasn't in use until the next version?

A great solution for a small feature and the only proper one.

**Comment by derletztekick** [comment]
I add a PR, see https://github.com/ilosuna/mylittleforum/pull/20

**Comment by derletztekick** [comment]
Done. Changes were merged to master.
