### ISSUE TITLE
further error in read-status-handling

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#245]
An read posting is marked as read and not as new. This works in the main views (thread and table) but not in the thread tree below the message in the single posting view.

See also [this and the following postings](http://mylittleforum.net/forum/index.php?id=10221) in the project forum (german language).

**Comment by auge8472** [comment]
After commiting the function for unification of the handling [I found a posting](http://mylittleforum.net/forum/index.php?id=10186) that showed me the necessity of the distinction between the opening posting and a new answer. With the special case of folded threads one will not see a new answer to a thread in the main view (except in the last entries box (when present)).

There are two solutions in my mind.

1. Reimplement the old behaviour with the described distinction between new-class for the opening message and an answer (simple).
1. Do not fold threads when a new/unread answer is present (not simple but *IMHO* favourable (seems much more sophisticated to me)).

**Comment by derletztekick** [comment]
> necessity of the distinction between the opening posting and a new answer

And we cannot add this issue to the new function, too? How could it work in case of folded threads?

**Comment by auge8472** [comment]
> > necessity of the distinction between the opening posting and a new answer
> 
> And we cannot add this issue to the new function, too?

We can add it to the function. The distiction was made with `if ($data['pid'] == 0)` and `$data` is one of the functions parameters. All necessary informations are available.

> How could it work in case of folded threads?

If a thread is folded, only the opening posting is visible and should therefore be marked as new in case of a new (hidden) answer. In case of unfolded threads this information (marking of the opening posting) is superfluous but a further additional distinction is one too much (IMHO).

To unfold a thread with a new answer in a forum with otherwise folded threads would be "the nice solution". That would need a lot more effort. Nothing for a primarily bugfix release.

**Comment by derletztekick** [comment]
> We can add it to the function. 

Okay, I check the following [code](https://github.com/ilosuna/mylittleforum/commit/9dab3e042d9ee8d35bb5b9c37fcdd50bca6b0636#diff-fe37dd6564d0036b00370f87c4d9e584L155) and rewrite the if-condition:

```
if (isset($_SESSION[$settings['session_prefix'].'usersettings']['newtime']) && 
    ($data['pid']==0 && isset($data['last_reply']) && $last_visit && ($_SESSION[$settings['session_prefix'].'usersettings']['newtime']<$data['last_reply'] || $last_visit && $data['last_reply'] > $last_visit)) || 
	(isset($data['time']) && $last_visit && ($_SESSION[$settings['session_prefix'].'usersettings']['newtime']<$data['time'] || $last_visit && $data['time'] > $last_visit) ))
```

Can you check this line for the [condition in function](https://github.com/ilosuna/mylittleforum/pull/255/files#diff-65d0f4ac62824915436134aefe2c4633R2838) file?

**Comment by auge8472** [comment]
I made a few tests in the project forum. As a not-logged-in user, I can write entries and refresh the main view to remove the new-status. But when I write anew entry in the same thread, *all entries are marked as new again*! Thats because the condition in the actual code (version 2.4.2, same code as in the new function in the repo) asks for `$data['last_reply'] > $lastVisit` **OR** `$data['time'] > $lastVisit` in *one* condition.

My proposal:

- a new optional function parameter `$folded = false`
- either a check for `$folded !== false` and the conditions for the opening posting including `$data['last_reply'] > $lastVisit` *and* the code for registered users for this branch
- or a check only for `$data['time'] > $lastVisit` for the answers *and* the code for registered users for this branch

The code itself will follow tomorrow.

**Comment by derletztekick** [comment]
> asks for $data['last_reply'] > $lastVisit OR $data['time'] > $lastVisit in one condition.

Not in my posted condition above. Here, `$data['last_reply']` is checked together with `$data['pid']==0`.

**Comment by auge8472** [comment]
> Or in other words, does this code works as expected?

I haven't tested it but it looks plauisible.

> If yes, use it in the new function.

I'll do.

**Comment by derletztekick** [comment]
> I haven't tested it but it looks plausible.

This should be the same as my "one-line-code".

**Comment by auge8472** [comment]
> This should be the same as my "one-line-code".

Yes it is, but it is far more readable than your one-liner. :-)

I want to add a further condition for opening postings (`$data['pid'] = 0`). The function parameter (proposal: `$folded` `true|false`) should act as a switch to distinguish between folded and unfolded thread trees or views.

~~~
function getMessageStatus($data, $lastVisit, $folded = false) {
	if ($data['req_user'] !== NULL and is_numeric($data['req_user'])) {
		/* … */
	} else {
		$data['is_read'] = false;
		if ($data['pid'] == 0 && $folded !== false) {
			/* … */
~~~

So it wouldn't hurt at the moment at any place, make a distinction between thread trees (in main view and single-entry-view (below the posting)) and nested-postings-view possible and give us the opportunity to add a handling of folded threads at a later point.
