### ISSUE TITLE
Tags for filtering and sorting bookmarks

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#254]
With a growing amount of bookmarks some users will need a function to keep the survey over it. I want to discuss the possibility to allow the user to tag her/his own bookmarks. With these tags she/he could filter the bookmark list or maybe order the bookmarks on the fly by the tag names.

**Comment by derletztekick** [comment]
I don't link the "feature". It seems to be opposed to "little".

**Comment by auge8472** [comment]
> I don't link the "feature". It seems to be opposed to "little".

__*zack*__ That to me, who opposed often enough to new proposals because of being not "little". Yeah, it's a different perspective as a developer. :-)

Yes, this would be a function wich *could* (not must) confuse inexperienced users and it would need additional infrastructure (art least one database table). On the other hand at least one user works with more than a few bookmarks what leads to confusion because of their amount (it's, what he reports).

We introduced bookmarks and got positive feedback, even it's seldom or never be used in many installations. But when it should be used, it should IMHO be usable at it's best, even with many bookmarks, even with bookmarks from long time ago (Why I bookmarked it? ;-)).

The folders, that magma proposed, are definitely to big for "little". The tags, which IMHO *in general* could play a bigger role in the forum software, are a thinkable approach, but maybe not the best.

I am strongly interested in Alex's opinion. @ilosuna?

**Comment by derletztekick** [comment]
In my opinion, the new bookmark feature is against the meaning of "little". Yes, I implement this feature but...  Currently, it's like: "The Fisherman and His Wife". ;-)

Tags (or folders) can be added simple, of course, but we have to implement a new search and sorting function, too. I don't use bookmarks and, I believe, 90% of the users don't use this feature. So, there is a misalignment/overhead between developing and benefit.

**Comment by derletztekick** [comment]
I add an new column `tags` to the bookmark table. Now, the user can add some kind of tags to the saved bookmarks. I also include a _filter-function_ (by clicking to a specific tag). Please check out the changes in https://github.com/ilosuna/mylittleforum/pull/287

**Comment by auge8472** [comment]
I tend to disagree on a new column `tags` in one of the existing tables. Tags are in a 1-to-n relation to bookmarks and to postings, where one can use them. I'll make a second proposal so we can compare and unify them.

**Comment by derletztekick** [comment]
Hi,

I add the new code, so you can start a new branch for "handling" tags in postings and bookmarks. The current implementation is equal to the postings. A better one may be the usage of a new table instand of the list in one column.
