### ISSUE TITLE
unused code for folded threads in entry.inc.tpl

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#257]
I found code for the handling of folded threads in [the namely file, line 82](https://github.com/ilosuna/mylittleforum/blob/master/themes/default/subtemplates/entry.inc.tpl#L82) of the default template. It sets a class (`{if $fold_threads==1} js-display-none{/if}`) to hide the answers of the thread in case of the (user) setting `folded_threads = true`.

**But** the matching PHP-file doesn't set `$fold_threads`, so this fragment of code will never been executed. Additionally I want to ask, if it is useful, to hide the thread tree when reading the entries one by one. If I open the entries one after the other, it is essentially necessary to access a link to every single entry in the tree below the message. A folded thread tree is useless at all in this case.

IMHO the code should be removed from `entry.inc.tpl`. Any thoughts?

**Comment by derletztekick** [comment]
Do you check [index.inc.php#L254](https://github.com/ilosuna/mylittleforum/blob/master/includes/index.inc.php#L254)?

**Comment by auge8472** [comment]
> Do you check index.inc.php#L254?

Yes, I did. But that's not the place to look.

The script `index.inc.php` works with `index.inc.tpl` and there you'll find the variable `$folded_threads` in the script and in the template. But I spoke about `entry.inc.php` and `entry.inc.tpl`. You'll find no occurence of `$folded_threads` or a different named variable for this purpose in the script `entry.inc.php` but you will find the orphaned variable in the matching template `entry.inc.tpl`.

**Comment by derletztekick** [comment]
I didn't find any other hit. So, yes, it can removed from the tpl.

**Comment by auge8472** [comment]
Thank you for your confirmation. I'll remove the code from the template. It's a pity that I was a bit to fast with the new release. But on the other hand it will not hurt anybody. :-)
