### ISSUE TITLE
Variable in lang file is not set

### ISSUE THREAD

**Issue by derletztekick** [ilosuna/mylittleforum#264]
During the update, I take notice of a missing variable `version`, see screen shot.

![mlf_update](https://user-images.githubusercontent.com/3595603/31358725-14572d0c-ad47-11e7-9d09-5a1ec17b515a.png)

**Comment by auge8472** [comment]
Och menno!

Not worth a new version. but will be included into the next maintenance release.

**Comment by derletztekick** [comment]
Solved by https://github.com/ilosuna/mylittleforum/pull/265
