### ISSUE TITLE
Tidying up the default theme sources

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#268]
There are a few places in the HTML-template-files with nested title-attributes. Tidied example from [the thread tree in index.inc.tpl](https://github.com/ilosuna/mylittleforum/blob/master/themes/default/subtemplates/index.inc.tpl#L45) (last link in the line):

~~~
<a href="index.php?mode=posting..." title="{#delete_posting_title#}"><img src="../images/delete_posting.png" title="{#delete_posting_title#}" alt="[x]" width="9" height="9" /></a>
~~~

The title-attributes for the images was introduced in mlf1 as a workaround for meanwhile ancient browsers, that showed the content of the alt-attribute when hovered with the mouse. This was prevented with the presence of an title-attribute. But the special case of titles in images as content of a link which itself has a title is meaningless. The example uses the same title string for the link and the image. But only one of the titles will be shown. The other one is superfluous.

In the case of different strings for link and image the situation tends to be faithless. Which of the titles pops up, which will never be shown? And as last, also in this case one of the titles is superfluous. So my proposal is to tidy up the theme templates in a first step and the language files afterwards.

I don't know which one to remove and which to keep but thats only a question of a test with a sample code and a general consideration about which point to tie the title (the surrounding or the contained element).

Any thoughts?

**Comment by derletztekick** [comment]
> Any thoughts?
No. Remove one of the title-attribute.

**Comment by auge8472** [comment]
> > Any thoughts?
> No. Remove one of the title-attribute.
Err, your sentence is an oxymoron. :-)

But yes, to remove one title is the goal. I tend to remove the title from the image. At first, the link is the functional element and should be the one with the title (if a title is appropriate) and at second, the workaround for showing the content of the alt-attribute on hover is not necessary anymore.

**Comment by loesler** [comment]
>  I tend to remove the title from the image.

Sounds very reasonable.

**Comment by auge8472** [comment]
IMHO we hit most of the occurences so it's time to close this issue. If we find further cases, we know, how to handle it.
