### ISSUE TITLE
Wrong(?) database query in admin.inc.php

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#272]
The block for activating or unlocking a user contains a perplexing query (actually [in line 870](https://github.com/ilosuna/mylittleforum/blob/master/includes/admin.inc.php#L870)). It begins with `SELECT  user_name, user_email` names the table (but without keyword `FROM`) and continues with `SET` and names several fields with their current or new values. The block itself is commented with `// Send notification to user` what leads IMHO to a `SELECT`.

Can you, @derletztekick or @ilosuna explain, what the code *should* do? I want to change it myself in the end, because I reformat the whole file and want to prevent interferences between my changes and someone elses change of the query.

**Comment by derletztekick** [comment]
Hej,

I believe(!), it is a copy and past error from the line ahead. The current query doesn't make sense. It should be replaced by e.g.:

`$user_result = mysqli_query($connid, "SELECT user_name, user_email FROM ".$db_settings['userdata_table']." WHERE user_id=".intval($_GET['activate'])." LIMIT 1");`

/Micha

**Comment by auge8472** [comment]
> It should be replaced by …

I will include it, when the reformatting is ready. Thank you.
