### ISSUE TITLE
Error "Field 'entries_read' doesn't have a default value" when trying to create a new user

### ISSUE THREAD

**Issue by fany** [ilosuna/mylittleforum#284]
Upon trying to submit the creation of a new user, I get the error message "Field 'entries_read' doesn't have a default value". (I use MariaDB with sql_mode STRICT_TRANS_TABLES activated.)

I can reproduce this with a fresh installation the current master 16dc507884e99dbdfc16c14d799b87a31984b279 as well as with release 2.4.6.

If I understand commit adbf9969623bcfe69e168077a55d00b204a21faa correctly, the column in question should no longer be present, anyway, so as a workaround I have now simply DROPped it.

Regards,
fany

**Comment by derletztekick** [comment]
Hi Fany,

I clean up the install.sql file and remove the column, see https://github.com/ilosuna/mylittleforum/pull/285

/Micha

**Comment by auge8472** [comment]
Added the bug-label only for later searches for labelled issues

**Comment by derletztekick** [comment]
Fixed in version [2.4.7](https://github.com/ilosuna/mylittleforum/releases/tag/2.4.7)
