### ISSUE TITLE
enclose strings in language files in quotes

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#298]
After introducing the language dependent word delimiters in the language files, I thought every when and then about the string. It's a space for most of the supported languages (i.e. [English language](https://github.com/ilosuna/mylittleforum/blob/master/lang/english.lang#L23)) and only [chinese language](https://github.com/ilosuna/mylittleforum/blob/master/lang/chinese.lang#L16) knows a few different chars as delimiter. The string for non-chinese languages contains several spaces behind the equals sign but that's "only" because of the string indentation.

As far as I investigated, the language strings get imported with [the Smarty function `configLoad`](https://www.smarty.net/docs/en/api.config.load.tpl) in [the index.php (lines 53 and 54)](url). [Config files for use within Smarty](https://www.smarty.net/docs/en/config.files.tpl) are allowed to enclose strings in single or double quotes.

> Values of config file variables can be in quotes, but not necessary. You can use either single or double quotes.

IMHO we should enclose the strings, because a config key that get's it's value more or less by accident because of the intendation feels wrong, looks wrong and *could* break.

I propose to enclose all strings with quotes with the exception of technical values like locales and time format strings. It would be a diligent but routine piece of work, but I would test it and do the work.

**Comment by derletztekick** [comment]
> but I would test it and do the work.

Fine! :-)
