### ISSUE TITLE
New user can not be registered

### ISSUE THREAD

**Issue by wqun** [ilosuna/mylittleforum#299]
> database error
> "Field 'entries_read' doesn't have a default value"

how can i do ,please

**Comment by derletztekick** [comment]
Hi Wqun,

please, delete this table column. It is not used any more and will be fixed within the next release, cf. https://github.com/ilosuna/mylittleforum/issues/284.

regards
Micha

**Comment by derletztekick** [comment]
Fixed in version [2.4.7](https://github.com/ilosuna/mylittleforum/releases/tag/2.4.7)
