### ISSUE TITLE
Missing entry in lang files

### ISSUE THREAD

**Issue by derletztekick** [ilosuna/mylittleforum#302]
In admin.inc.php, there is a call to a _missing_ lang entry `$lang['error_input_too_long']` in [line 882](https://github.com/ilosuna/mylittleforum/blob/master/includes/admin.inc.php#L882). It should be replaced by `$lang['error_username_too_long']`, shouldn't it?

**Comment by auge8472** [comment]
Will check it because I'm always in the language files.

**Comment by derletztekick** [comment]
Thank you!

**Comment by auge8472** [comment]
I can confirm your observation. Please add the necessary change as a pull request. I am occupied by the problem with the merge conflict of pr #300 **\*garglarks\***

**Comment by derletztekick** [comment]
Okay, I will change the key from `error_input_too_long` to `error_username_too_long`.

**Comment by derletztekick** [comment]
Done by #304
