### ISSUE TITLE
HTTP-Status 403 since 2017-12-26

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#314]
@ilosuna: Since the afternoon of 2017-12-26 (CET) I get status *403 forbidden* for  requesting the forum (mylittleforum.net/forum).

**edit** One gets the 403-status on the whole domain, not only in the forum.

**Comment by auge8472** [comment]
After seven days: Since my alarm notice retrieved no answer yet, I want to announce the opening of an *interim project page*. Even it's a german domain, the content is in english language. This is **no attempt** to take over the project leadership but I'm convinced that we need a reachable home for the project. If and when @ilosuna states the re-availability of the original project page (mylittleforum.net), we will merge the contents (prevalent the contents of the forums) again.

The page is reachable under the domain [projekt-mlf.de](https://www.projekt-mlf.de/) and contains also [an interim project forum](https://projekt-mlf.de/forum/).

**Comment by derletztekick** [comment]
> The password must contain at least 12 characters

Are you sure that this setting is user-friendly?

**Comment by auge8472** [comment]
> > The password must contain at least 12 characters
> Are you sure that this setting is user-friendly?

**IMHO** the default of eight chars is to short. Where would you set the lower limit?

**Comment by derletztekick** [comment]
> IMHO the default of eight chars is to short

Together with the salt?

**Comment by auge8472** [comment]
> > IMHO the default of eight chars is to short
> Together with the salt?

The salt is not part of the password itself. It's "only" part of the stored hashed value. Should we take it's length into account when counting the length of the password?

**Comment by derletztekick** [comment]
I don't know, but if the length of the password is too large, the password is only in a technical sense "safe".

**Comment by auge8472** [comment]
> if the length of the password is too large, the password is only in a technical sense "safe".

Isn't the goal of longer passwords to make it harder to brute force it? This is "safer in technical sense" at it's best. Common actual password managers which creates passwords/passphrases uses much bigger lengths. Often they *recommend* lengths of 64 or at least 48 chars but allow the use of shorter strings.

Anyway: I resetted the minimal length of the password to 8 chars.

**Comment by derletztekick** [comment]
> This is "safer in technical sense" at it's best. 

Yes, in a technical sense but not in a humanly one. Restrictions for passwords (e.g. length, special characters, expiration date etc.) motivate the user to write down the password. A long password written down on a post stick of your monitor may safe in technical sense but is it relay safe? :-)

**Comment by auge8472** [comment]
Well, if the note is only accessible by the user, it's no problem to write down the (longer) passwords. 18 Years ago I had a DIN-A-4 paper with all my user names and passwords on my desk (at home!). And yes, I know the memes with pictures of bureaus with large papers with all the access data on the walls. :-)

**Comment by derletztekick** [comment]
Set it to 12, I will think over compatible password ;-)

**Comment by derletztekick** [comment]
I create a new account but I didn't receive a confirmation mail. The mail-server is running?

**Comment by ilosuna** [comment]
I'm sorry! It seems like there was a change in the ownership of the web-hosting provider (speicherzentrum.de) at some point last year. Then the _403 forbidden_ problem occurred while I was on holidays. Last week I tried to contact the support without success. I have no access via FTP at the moment but I could make a database backup in the administration panel. Currently I'm transferring the domain to a domain name registrar. I would then set up a web-server and restore the database. @auge8472: What about if the domain mylittleforum.net would point on your server where you installed the interim project forum? Either way I think it's in better hands under your control. I could also pass you the database backup (maybe I should clear/anonymize the user data because of data privacy concerns).

**Comment by auge8472** [comment]
Hello Alex

I'm glad to read from you. Feared that you are not doing well because of the long time of silence. I will write you an e-mail to discuss the other points. This platform is IMHO the wrong place for such discussions.

**Comment by auge8472** [comment]
After the import of all relevant messages, that belongs to MLF, excluding the messages about my theme and the outage of mylittleforum.net, from the forum on projekt-mlf.de to the one on mylittleforum.net, IMHO everything is done. I will close now this issue.
