### ISSUE TITLE
Empty variable $categories causes warning and in consequence not sending headers

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#316]
With `display_errors = on` (PHP 7.2) a forum without categories reports a warning about variable `$categories` is not countable when calling PHP-function `count` [in `index.php` line 75 (in version 2.4.6)](https://github.com/ilosuna/mylittleforum/blob/2.4.6/index.php#L75). This happens because the variable will be initialised even without categories [in `includes/main.inc.php` line 101](https://github.com/ilosuna/mylittleforum/blob/2.4.6/includes/main.inc.php#L101).

~~~
Warning: count(): Parameter must be an array or an object that implements Countable in …index.php on line 75
~~~

I tested with a improved check [in `index.php` line 72](https://github.com/ilosuna/mylittleforum/blob/2.4.6/index.php#L72) that checks not only for the existence of the variable but also for it's non emptyness.

~~~
if (isset($categories) and !empty($categories)) {
~~~

[The function `get_categories`](https://github.com/ilosuna/mylittleforum/blob/2.4.6/includes/functions.inc.php#L138) itself [returns `false` in case of no categories](https://github.com/ilosuna/mylittleforum/blob/2.4.6/includes/functions.inc.php#L168). It might be better to check against the return values (array or `false`) instead of `!empty`.

**Comment by auge8472** [comment]
@derletztekick Did you get the message I sent with the contact form on your site?

**Comment by derletztekick** [comment]
Yes, I got your mail and wrote an answer today.
