### ISSUE TITLE
Changing personal settings affects only the actual session

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#317]
After installing a version 2.4.6 yesterday (2018-01-01) I logged in and changed several settings. Then I went to the personal settings and changed i.e. the language for my personal use. Today I became aware, that my personal settings was not the way I set them yesterday. They all are stuck to the general forum settings.

After changing them again, I get the forum in my selected language but the settings form states, that the general language setting is selected. After log out and log in again the forum is presented with the general language setting again.

I don't know, if this is an issue with my webspace and/or installation or a general issue. Will dig into it.

**Comment by auge8472** [comment]
Digging the code showed a problem with the field `mlf2_userdata.birthday`, which gets, when no birthday date is given, the **invalid value** `"0000-00-00"` (MySQL 5.7.20). The field allow the default value `NULL`. Will set it as default for no given birthday date.

**Comment by derletztekick** [comment]
Do you check the SQL statements/PHP code for Null-values, too? If yes, set the default value to Null.

**Comment by auge8472** [comment]
> Do you check the SQL statements/PHP code for Null-values, too?

No, didn't check it until now.

> If yes, set the default value to Null.

For clarification: The database field *itself* [has the default value `NULL`](https://github.com/ilosuna/mylittleforum/blob/master/install/install.sql#L8) (`birthday date NULL default NULL`). It might be possible, that one or another place, where the birthday should be displayed, doesn't consider this possible value. Will dig into it.

**Comment by derletztekick** [comment]
> For clarification:

Okay, thank you. In this case: Change the default value of the column.

**Comment by auge8472** [comment]
> In this case: Change the default value of the column.

Seriously? In my work with database systems (MySQL and MS SQL) everyone™️  recommends to set default values to `NULL`, where possible and appropriate. The excessive use of empty strings as default values in the database structure of My Little Forum is IMHO a not recommendable way but not changeable because of legacy reasons.

I would rather search for the two or three places (in case of the birthday date), where I have to check for a proper handling of `NULL` values instead forbidding them.

**Comment by derletztekick** [comment]
> Seriously? 

Well, you can always check your changes by installing a modified version... ;-)

**Comment by derletztekick** [comment]
I cannot create an account because of an error:

```
MLF project forum
Database error!

Field 'entries_read' doesn't have a default value
```
We should fix it - see https://github.com/ilosuna/mylittleforum/issues/299 or https://github.com/ilosuna/mylittleforum/issues/284

**Comment by auge8472** [comment]
It is fixed. But it's fixed after the release of 2.4.6. :-(

I'll delete the column in my installation.

**Comment by derletztekick** [comment]
> But it's fixed after the release of 2.4.6. :-(

Yes, my fault! :-( We should release a fixed version...

**Comment by auge8472** [comment]
> Yes, my fault! :-( We should release a fixed version...

You are right. It wasn't clear to me that this is a real show stopper.

**Comment by auge8472** [comment]
Notice to me: The user edit form of the admin panel shows the same problem as the users user edit form.

**Comment by derletztekick** [comment]
Hmm, I cannot reproduce the error on your installation @ https://projekt-mlf.de/forum/

My language is german, my signature is saved etc.

**Comment by auge8472** [comment]
Yes, the error is solved in user.inc.php with a hotfix. But when I want to change your rank in the admin panel, it fails. My assumption is that it is because of the birthday issue. :-)

**Comment by derletztekick** [comment]
This seems to be [solved](https://github.com/ilosuna/mylittleforum/issues/320) or do you have still problems to save the user data?

**Comment by auge8472** [comment]
I added the hotfix also to `admin.inc.php` in my installation and was able to change your rank after activating the default template for my own account. I have to add a clean version of the bithday-fix to the repository. After that, I can pack a new release.

**Comment by derletztekick** [comment]
Fine!
