### ISSUE TITLE
No CSRF-token for user edit form in the admin panel

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#320]
Beside the problem with the users birthday date (when not given, see #317) there seems to be an additionally issue with the user edit form in the admin panel. When the user edit form gets submitted the submit button has the name `user_edit_form`. The script `admin.inc.php` checks its presence [in line 111](https://github.com/ilosuna/mylittleforum/blob/master/includes/admin.inc.php#L111) but it checks also for the CSRF-token (`$_POST['csrf_token']`) which every form should have.

The problem is, there is no token. I would expect to find a form field because of `$_POST['csrf_token']` but there is none. Where do I find the definition and HTML-rendering of the token?

**Comment by derletztekick** [comment]
In [L475](https://github.com/ilosuna/mylittleforum/blob/master/themes/default/subtemplates/admin.inc.tpl#L475) is a definition of the input-field. There are three more hits. I believe, you are looking to the wrong code/file.

**Comment by auge8472** [comment]
> In L475 is a definition of the input-field.

It's for another form but thanks for pointing me to the example.

> But yes, we should add the token [there] too.

I'll add it.

**Comment by auge8472** [comment]
OMG! The problem is not with the forum scripts or the default template, it is a problem of my own template. I forgot to add the fields for the CSRF-tokens at several places (also for [the user-edit-form in the admin panel](https://github.com/auge8472/mlf2-themes/blob/master/responsive_1/subtemplates/admin.inc.tpl#L535)).

So I have to solve it in the theme (tag: invalid) and to add the token-(field) at the place, @derletztekick mentioned (tag: enhancement).

**Comment by auge8472** [comment]
**Ahem**, see therefore also #196 **mumble, garglarks** :-)

**Comment by derletztekick** [comment]
Do you add the token to the default template, i.e. `user_edit.inc`?

**Comment by auge8472** [comment]
Yes, I'll do.

**Comment by derletztekick** [comment]
add token, [done](https://github.com/ilosuna/mylittleforum/pull/336).
