### ISSUE TITLE
Minimal system requirement: PHP 5.4

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#325]
With the introduction of the new tag handling we use [a syntax for initialising an array](https://wiki.php.net/rfc/shortsyntaxforarrays), that was [introduced with PHP 5.4](https://wiki.php.net/rfc/shortsyntaxforarrays#conclusion). That leads to error messages in older PHP versions i.e. [in line 1593 of `functions.inc.php`](https://github.com/ilosuna/mylittleforum/blob/master/includes/functions.inc.php#L1593).

Because of the ancient status of these *very* outdated PHP versions IMHO the right way is to set the minimal version to PHP 5.4 in the readme and to document it also in the wiki.

**Comment by auge8472** [comment]
Corrected the [release message](https://github.com/ilosuna/mylittleforum/releases/tag/2.4.7) and the [installation](https://github.com/ilosuna/mylittleforum/wiki/Installation) and [update](https://github.com/ilosuna/mylittleforum/wiki/Update) instructions.

**Comment by derletztekick** [comment]
Add new version to [readme](https://github.com/ilosuna/mylittleforum/blob/master/README.md)

**Comment by auge8472** [comment]
I will add a message in the project forum and close this issue.
