### ISSUE TITLE
Listing of entries with a specific tag failes with MySQL 5.7 (in my configuration?)

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#326]
The MySQL installation of my webhosting service seems to be *very* strict. If I klick on a tagin the tag cloud to list all entries with this tag, the database query fails with the followin error message.

~~~
Expression #2 of ORDER BY clause is not in SELECT list, references column 'ft.time' which is not in SELECT list; this is incompatible with DISTINCT
~~~

The name `ft`is the alias of `mlf2_forum_table`. The named field `ft.time` itself [is really in the SELECT list](https://github.com/ilosuna/mylittleforum/blob/df80e8140ba933fc0237b115dc3c40f7f41c88b2/includes/search.inc.php#L200), but has the alias `time` (without the leading table alias). In the ORDER clause it is named `ft.time`. Will test it with changed names.

**Comment by derletztekick** [comment]
> in my configuration?

Unfortunately, [no](https://www.projekt-mlf.de/forum/index.php?id=11)
