### ISSUE TITLE
Users can have avatars, let's show them more often

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#330]
Registered users can upload an avatar image. The admin can decide to show them in the postings and on the users profile page, on the profiles page only or not at all. I want to propose to show the avatars also in the user list, in the currently-online-list and in the `#usermenu` in front of the user name.

To align the user names in the list(s) I want also intruduce a placeholder for users that have not uploaded an avatar image. I made a simple graphic in the size of 128x128 and a smaller one with 32x32 pixel.

Small version (436 bytes):

![avatar-placeholder-32](https://user-images.githubusercontent.com/1734660/34940922-c532b8b6-f9f1-11e7-8cd7-105ae26789e3.png)

**Comment by derletztekick** [comment]
>  in the currently-online-list

Are you sure? If e.g. 200 users are online, you will load and display 200 128x128 px images?

**Comment by auge8472** [comment]
> > in the currently-online-list
> 
> Are you sure? If e.g. 200 users are online, you will load and display 200 128x128 px images?

I have never seen myself a MLF-forum with more than fifteen to twenty users online at the same time. But yes, this would be a problem if there were 200 users, even it is expectable, that many of them had no own avatar so their avatar would be *the one* placeholder. But with only 50 distinctive avatars with 15kB filesize each, the forum would cause additional 750kB traffic (not taking caching into account).

**If** the avatars should be displayed at additional places, the forum needs an enhanced image handling after the avatars upload. This could be a resizing of the image not only to the maximum lengths of height and width but also a resizing to 32x32 and 64x64 pixels (arbitrary but often seen selection of the values).
