### ISSUE TITLE
Unsubscribing from an e-mail-notification

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#331]
Make it possible to unsubscribe from an e-mail-notification. Actually it is only possible while editing of postings is allowed in the posting form.

**Comment by auge8472** [comment]
Would it be enough to provide an unsubscribing link in the e-mail or should we add a page with the subscriptions, where the user can unsubscribe a thread? providing the link seems to me the simplest way. I would expect such a link exactly there.

**Comment by loesler** [comment]
> Would it be enough to provide an unsubscribing link in the e-mail 

Yes, I think so.

**Comment by auge8472** [comment]
> > Would it be enough to provide an unsubscribing link in the e-mail
> 
> Yes, I think so.

Hehe, why you didn't close the issue? It is done, isn't it? :-)

**Comment by loesler** [comment]
I wasn't sure, if you still wait for an answer.
