### ISSUE TITLE
Alien string "Bookmark" in german language file

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#332]
I would like to translate the string "Bookmark" in all it's occurences to it's german equivalent "Lesezeichen". Bookmark itself is common in german language because of it's use on websites (where it's derived from the use in browser programs with untranslated UI). But in contrast to "Sidebar" which would sound a bit strange as "Seitenleiste" a "Lesezeichen" is *IMHO* in general much more common than "Bookmark" for german speakers and readers.

Opinions?

**Comment by derletztekick** [comment]
Favoiten

**Comment by auge8472** [comment]
> Favoriten

Oh, a IE-user. ;-)
