### ISSUE TITLE
Missing MySQL-resultset in function call in bookmark.inc.php

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#334]
The function call of `mysqli_free_result` [in line 216](https://github.com/ilosuna/mylittleforum/blob/master/includes/bookmark.inc.php#L216) throws an error *every when and then*. [The function](http://www.php.net/mysqli_free_result) has to have one parameter, a result of a previous operation. It seems that sometimes the result (normally stored in variable `$bookmark_result`) does not exist. In the block exists another result set (`$order_result`). Is eventually *this* variable meant (a simple copy'n'paste error?)?

~~~
[19-Jan-2018 …] PHP Warning:  mysqli_free_result() expects parameter 1 to be mysqli_result, null given in /…/forum/includes/bookmark.inc.php on line 216
~~~

@derletztekick You know your code. Is it really a simple copy'n'paste error or is there anything else, I don't see?

**Comment by derletztekick** [comment]
[Done](https://github.com/ilosuna/mylittleforum/pull/335).
