### ISSUE TITLE
Discussion of project and repository organisation

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#343]
Because I want to begin with the implementation of new features (the return of the project page got me hooked on it), I want to discuss the organisation of the work. This is not about who does what. It is about the questions if and how to support a stable branch (at the moment 2.4.x) and simultaneously developing new things in a different branch (at the moment for 2.5) and how to isolate these branches for *preventing interferences*.

I have a few *proposals* for it. Example version numbers are borrowed from the actual situation (stable version: 2.4.7).

- **Which versions to support?** From version 2.5 on we support the actual branch (2.5) with features and fixes and the last branch (i.e. 2.4.x) with security relevant fixes and fixes for show stoppers (should not occure). Fixes are developed within the actual development branch (for 2.5) and are transferred to the last (old) branch (for 2.4.x) with [cherry picking](https://git-scm.com/docs/git-cherry-pick) or in cases of code conflicts by hand.
- **How to structure the repository branches?** When beginning with the work on a new main version (2.5) the old stable (2.4.x) get it's own lasting branch from where new maintenance versions (i.e. 2.4.9, etc.) can be tagged. Also the new main version get's an own branch (i.e. `dev_2.5`).
- **Handling of the main branch for the new version.** All pull requests residing in extra branches and are targeted against the branch for the new version (`dev_2.5`). When the new *main* version (2.5) is ready, it can be merged into the master. When the decision for the *next* main version (2.6) is made, the last main version (2.5.x) get it's own lasting branch (like we did for version 2.4.x before).
- **When an old version get's retired?** As long as version 2.5 is the actual version, we should *IMHO* provide also security fixes for the 2.4-branch. This should be sustainable because we will have the fixes in the actual branch. When a new main version (2.6) is ready, the 2.4-branch get retired and the 2.5-version, which is the actual version in this moment get branched and will be "the old supported version".

Yes, this is a bunch of rules. But I think, if we went to go on with the development, we need a separation of stable and development branches, even if we decide not to support the last main version branch (2.4.x when 2.5 is actual and until 2.6 is ready).

---

For the purpose of making the issues and pull requests more distinguishable I created a few new tags (discussion, feature, next major version, work in progress).

**Comment by danielb987** [comment]
I'm quite new to git and GitHub, but my recommendation is to use the "master" branch for new development. To that branch everyone do their pull requests.

Then a new version is to be released, a new branch could be created for that version. And that only a few persons cherry pick commits to old branches. (That I mean is that most developers should not care at all about those branches).

That way, it will be easy for everyone, including newbies, on which branch to send pull requests to, and which branch to use to update their own branch.

You can then refer to the master branch for everything:
* Send pull request to master branch.
* Update your branch from the master branch.

If developers needs to do think of which branch to clone from, or which branch to send pull requests to, the risk of errors increase. If everyone always uses the "master" branch, there is less risk of error.

**Comment by auge8472** [comment]
@danielb987 Thank you for your opinion. Sounds reasonable to use `master` furthermore for the actual development until the development of a new main version begins. Less confusion, simpler inclusion of new participants.

**Comment by auge8472** [comment]
Ok, I want to start and with the exception of @danielb987 noone discussed the issue. Following daniels proposal I created the [branch "legacy_2.4"](https://github.com/ilosuna/mylittleforum/tree/legacy_2.4) which contains the actual stable version and should hold the necessary changes for further bugfix versions in the 2.4.x-branch. The development of the next main version takes place as ever in the master branch as it's base. Features get their own branches during development and will be merged into master, when ready.

I hope, this is ok.
