### ISSUE TITLE
Introducing e-mail transmission via SMTP instead PHP's mail function

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#348]
Several forum operators asked for e-mail-transmission with a SMTP-class. Several reasons was expressed. Servers without access to sendmail (or another e-mail-server), grey- or blacklisted hosting services (for what reason ever) and so on.

@ilosuna proposed to use [PHPMailer](https://github.com/PHPMailer/PHPMailer). I took a look into it and expect it to be manageable even without composer etc.

**Comment by auge8472** [comment]
Issue #238 depends on this feature.

**Comment by loesler** [comment]
Done by https://github.com/ilosuna/mylittleforum/pull/498
