### ISSUE TITLE
Type error in main.min.js

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#35]
The browser console of Firefox (v49) reports a type error in js/main.min.js, line 1, row 5393 and points me [to this MDN page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Var_hides_argument). Is this serious or is it something, we can ignore?

**Comment by derletztekick** [comment]
No entry in Opera's console, no entry in Firefox (49.0.1) console?! Can you replace the min-version by the readable main.js?

**Comment by auge8472** [comment]
Sorry, I forgot to say, that the message occurs in the project forum, that's driven with version 2.3.5.

**But:** I can confirm to see the same message in my own test forum for the file `main.js` (not minified). The message points to line 848, where a variable is declared with `var templatePath = templatePath?templatePath:"";` while a function parameter with exactly the same name is declared only one line before.
