### ISSUE TITLE
Providing width and height attributes for images in entries

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#356]
It's to prevent the entries stotting when loading images one by one to the entries. Especially when viewing a whole thread in nested or plain view, a thread with many entries with many images will jump and stot like hell.

With width and height attributes for the images, the browser will allocate the space for the images in the viewport.

**Comment by loesler** [comment]
How do you want to estimate the image size, if the file is located on an external server?

**Comment by auge8472** [comment]
I can't and I don't. But for uploaded images it's possible.

**Comment by loesler** [comment]
> But for uploaded images it's possible.

Yes, but if we take a look to [this posting](https://mylittleforum.net/forum/index.php?id=10530) and  the [image problem](https://mylittleforum.net/forum/index.php?id=10546), the thread opener has problems with external resources. Your suggestion is a drop in the bucket because most of the images aren't store at the forum server.

**Comment by auge8472** [comment]
You are right. For images, that are included into the entries of a forum, loaded from external sources and not from uploads, the script can't detect the width and height. In forums, where most or all images get loaded from external sources, the views still will jump. In case of the OP this seems to be the case.

Nevertheless the script should detect the values and insert the attributes, where possible. In other cases than Magma's forum operators may only accept image inclusions from uploads or at least uploaded images represent the majority of included images. There the attributes will enhance the situation.

**Comment by loesler** [comment]
> You are right. [...] the script can't detect the width and height

That's the point, exactly. Btw: I disable the function to upload images to the forum server. I believe, most administrators have these option disabled. I'm sorry, I cannot realize an added value for your suggestion. Of course, you can implement it but in most cases, it will useless.

**Comment by auge8472** [comment]
Solved with 1e80230 for 2.5 and 229753bd9 for 2.4.x.
