### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by KawaxJM** [ilosuna/mylittleforum#359]
Hi,
Updated from 2.3.4 to 2.3.5, then from 2.3.5 to current version 2.4.8,
When I want to update I get the error message:   **Database error in line 232:** 
That's all.
Any clue?
Thx in advance

**Comment by loesler** [comment]
Error message?

**Comment by KawaxJM** [comment]
No error message, just what I mentioned.

**Comment by KawaxJM** [comment]
To be complete I uploaded the three files on the server then started update_2.3.5-2.4.php (version 2.4.8), entered my password then got that message.  but it was left blank after the semicolon.

**Comment by KawaxJM** [comment]
![image](https://user-images.githubusercontent.com/37000890/36922382-e6a90d98-1e67-11e8-972a-65ba1c50617d.png)

**Comment by loesler** [comment]
Hmm, do you have phpmyadmin or any other tool to administrate your sql? In [line 232](https://github.com/ilosuna/mylittleforum/blob/master/update/update_2.3.5-2.4.php#L232), the following sql query should be executed:

`ALTER TABLE ".$db_settings['userdata_table']." CHANGE last_login last_login timestamp NULL default CURRENT_TIMESTAMP`

The value in `".$db_settings['userdata_table']."` contains the user-data table. The name depends on your table prefix. Can you manually execute this query?

**Comment by KawaxJM** [comment]
Thx Micha.
My database is fbsc, so the table is fbsc_userdata.
I used phpMyAdmin to enter the following SQL : ALTER TABLE fbsc_userdata CHANGE last_login last_login timestamp NULL default CURRENT_TIMESTAMP
This seemed to work // other syntaxes had failed before.
But when I launch the upgrade, I get the same error at line 232 back.
I'm hosted on oxito.com / php version should not be a problem.

**Comment by auge8472** [comment]
Assumed, that the script included the table name in a correctly manner into the query string, your query is *exactly* the same than the one, the script created. I've absolutely no idea, why the error occurs.

> I'm hosted on oxito.com / php version should not be a problem.

Your MySQL server is of which version?

---

Would you please be so kind to perform an update from 2.3.5 to [2.3.6.1](https://github.com/ilosuna/mylittleforum/releases/tag/v2.3.6.1) in a first attempt? Please mind the update script name `update_2.x-2.3.php` being the correct one. If the same error occurs and the error is a database problem, the mentioned code line will be 837 because of the questionable query being in [line 835](https://github.com/ilosuna/mylittleforum/blob/17516e3ae9e4ed411cf677533e638029395bee53/update/update_2.x-2.3.php#L835).

**Comment by loesler** [comment]
... and can you add an `echo` in line 231, i.e.

`echo "ALTER TABLE ".$db_settings['userdata_table']." CHANGE last_login last_login timestamp NULL default CURRENT_TIMESTAMP";`

to check the statement?

**Comment by KawaxJM** [comment]
Thx Auge and Micha,
MySQL is 5.7
Error is : **Database error in line 838:**   
because I added the extra echo line just before.
Echo gives 
**ALTER TABLE fbsc_userdata CHANGE last_login last_login timestamp NULL default CURRENT_TIMESTAMP**
I deleted the users with last_login being null, maybe this would help. but no success.
What puzzles me is that the SQL command in the console works ! At least it is what the console says :
![image](https://user-images.githubusercontent.com/37000890/37159244-a18aeb98-22ed-11e8-878f-2a90b0ca3e98.png)
Assuming that the SQL command was correctly executed in the SQL console and that it is the last SQL command of the 2.3.61 upgrade (the real last command being the update of the version number, shall I inactivate the line and rerun the script in order to have it completed ?

**Comment by KawaxJM** [comment]
From the table structure, I can see this:
![image](https://user-images.githubusercontent.com/37000890/37160411-7081235c-22f0-11e8-86e8-d09a1064faae.png)

**Comment by auge8472** [comment]
> Assuming that the SQL command was correctly executed in the SQL console ...

Your screenshot of the table structure shows, that the structure is adapted to the needs of version 2.3.6.1.

> ... and that it is the last SQL command of the 2.3.61 upgrade

At least it's the only operation to change any tables structure.

> ... (the real last command being the update of the version number, shall I inactivate the line and rerun the script in order to have it completed ?

I would tend to *yes*. Please perform a backup of the database before.

**Comment by KawaxJM** [comment]
Hello,
I changed the version number manually because it blocked.  Then I tried the most recent upgrade (2.4.8)  and I got error at line 238.  
Thinking about it, the error message shoud be :  **'Database error in line '.__LINE__.': ' . mysqli_error($connid);**
Obviously, the last part of it is missing on screen :
![image](https://user-images.githubusercontent.com/37000890/37215926-afffd266-23b9-11e8-9c86-1042e1d30a1e.png)
Could it be linked to something happening with **$connid** ?  This would explain why the SQL command succeeds when manually executed in the console.  The weak point of this explanation is that it is not the first occurrence of $connid (there is already one at line 225).

**Comment by KawaxJM** [comment]
A faster solution would be to install a fresh db directly on a 2.4.8 install, but then, how can I easily import the data ?  Meaning the settings, the userdata and the discussion threads ?  (Note that there are not so many threads as I just cleaned a big part of it.)

**Comment by KawaxJM** [comment]
OK I created a new install and a new db and switched to PHP 5.4 on the server.
I imported the table userdata // had to delete the 35th field, **entries_read**, that does no longer exist in version 2.4.8.  Some data are different, e.g. some birthday date being null instead of the 00.0000.000 format in the new version, but it does not seem to be an issue.
Is it all I have to do for user data ?
What table should I import to retrieve the threads and posts ?  If it is too complicate, I will consider starting from scratch.

**Comment by scottmx81** [comment]
I am also trying to upgrade from 2.3.5 to 2.4.8 (recently upgraded from 2.2.7 to 2.3.4 then 2.3.5) and I have the same problem. But in my case it is showing a more specific error:

`Database error in line 232: Invalid default value for 'birthday'`

**Comment by loesler** [comment]
@scottmx81 are you sure? In [line 232](https://github.com/ilosuna/mylittleforum/blob/master/update/update_2.3.5-2.4.php#L232), no birthday value/column is used. Do you have some birthday values like '0000-00-00'? If yes, please set these values to NULL.

@KawaxJM do you have another (test) server, e.g. a local server like XAMPP? Maybe, you can update the SQL tables on your local machine in a more secure way.

**Comment by KawaxJM** [comment]
I started to import the most important data to my fresh install rather than trying to upgrade the DB, I know that this kind of issue can take years to be solved !   Thx for your support anyway !

By the way, is this a small bug of v.2.4.8 ? In my old version, avatars were saved in **/images/avatar** under the file name **[UserID].png**.  With version 2.4.8, the images are saved to the same folder but under file name syntax **[UserID]_XXXXXXXXXX.png** with as result that the file does not get matched with the user ID.  When I set the file name to **[UserID].png**, then the image gets matched with the user profile having the same ID : the images appears subsequently in the profile of the user.

**Comment by KawaxJM** [comment]
OK nevermind, I had forgotten to CHMOD back the avatar folder to 777 !  Now it's working.

**Comment by auge8472** [comment]
> By the way, is this a small bug of v.2.4.8 ? In my old version, avatars were saved in /images/avatar under the file name [UserID].png. With version 2.4.8, the images are saved to the same folder but under file name syntax [UserID]_XXXXXXXXXX.png with as result that the file does not get matched with the user ID.

For explanation: We amend a timestamp to the user-id in the filename because of caching issues in browsers.

In some cases a new avatar gets not recognised when it has the same name as the old one. Some servers seems not to send the correct chache headers. To prevent this, we made the file name unique. The project forum stores avatars with the old *and* the new name scheme and displays them with both schemes.
