### ISSUE TITLE
Remove Flash button

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#376]
The Flash-button does not work since a long time. [We decided to remove the button](https://mylittleforum.net/forum/index.php?id=10621) a few months ago. I add a notice now, before we forget it again and again and again ...

**Comment by loesler** [comment]
I removed the flash button and flash option. Please note: The update script to version 2.5.x contains wrong version numbers and must be modified!!!

Done by https://github.com/ilosuna/mylittleforum/pull/390

**Comment by auge8472** [comment]
There are several changes, primarily implemented for the 2.4.x-branch, that isn't reflected in the master (2.5-er) branch. There is a bunch of work to get the actual master working after it's installation or an update. Thank you for your work and the mention.
