### ISSUE TITLE
Registration Error

### ISSUE THREAD

**Issue by PhilDunphy** [ilosuna/mylittleforum#383]
When registeirng a new user I get an Error stating not all from fields are filled. Inspection shows 2 hidden fields for a phone number and repeat email with a value of the admins email. Any ideas?

**Comment by loesler** [comment]
Do you use firefox browser with auto-complete? Maybe, you have the same problem like [Auge](https://mylittleforum.net/forum/index.php?id=10727). We have propose a [possible solution](https://mylittleforum.net/forum/index.php?id=10732) but we didn't implement it yet.

**Comment by PhilDunphy** [comment]
@loesler Yes the issue only occurs in FF. Switched to Chrome and registration works fine

**Comment by auge8472** [comment]
fixed with #387
