### ISSUE TITLE
Set minimal time for a forms roundtrip. Where do we need it?

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#406]
## Preamble

As we (@Helmut01, @loesler and me) discussed it in #402 the introduction of lower time limits for sending a form is recommended. That way fast sending bots, which returns a form within milliseconds, should get sorted out.

## For which cases the feature should get implemented?

These are the cases I found.

- registrate an account
- create a posting (registered and unregistered)
- sending an e-mail

Anything I forgot?

## What should be the limit?

@Helmut01 recommended one second because his measurements states the bots to send the fields within milliseconds (bot < 1 sec. < human). I myself would set the limit to a higher value. IMHO noone (human) will send the fields within a few seconds. So I would recommend something between 2 and 10 seconds and maybe making it dependent from the case (posting, registration, contact form (e-mail)).

Further opinions?

## How to implement it?

We can use the session of the user to store a the information about the requested form (the CSRF-token), and the time of the request (a timestamp). Whit this information we should be able to check the next matching request for the time since the first request and to sort out to fast second requests.

Does anone have another idea?

**Comment by loesler** [comment]
Hi,

this _feature_ is [already implemented](https://github.com/ilosuna/mylittleforum/blob/master/includes/posting.inc.php#L510) in `posting.inc.php`, i.e.,

`$_SESSION[$settings['session_prefix'] . 'formtime'] = TIMESTAMP;`

Currently, the minimal time difference [is set to 10 sec](https://github.com/ilosuna/mylittleforum/blob/master/includes/posting.inc.php#L601). 

However, this is a _local_ solution and I prefer a solution, which can be used for registration (and mailing), too.

If we add the following code in `main.inc.php` 

```php
// SPAM protection (Time (difference) between page reload)
if (isset($_SESSION['receipt_timestamp']) && intval($_SESSION['receipt_timestamp']) > 0) {
	$_SESSION['receipt_timestamp_difference'] = $_SERVER['REQUEST_TIME'] - $_SESSION['receipt_timestamp'];
}
$_SESSION['receipt_timestamp'] = $_SERVER['REQUEST_TIME'];
```
we have a global (session) variable `$_SESSION['receipt_timestamp_difference']` that can be checked against a meaningful threshold - whenever/wherever we need it, e.g.

```php
if (!isset($_SESSION['receipt_timestamp_difference']) || intval($_SESSION['receipt_timestamp_difference']) < $EPSILON) { /* error */ }
```

I can add this few lines of code to the software, if you want. 

/Micha

**Comment by auge8472** [comment]
What is with multiple browser tabs or windows? I can open several postings in different tabs and replying to these postings in these tabs. This could lead to open a new tab (generating a new timestamp) and sending a reply in the next moment from another tab. In this case the measured time could lie under the hardcoded 10 seconds and as the result the reply get rejected.

IMHO we need a further information about the before requested page, or am I wrong?

**Comment by loesler** [comment]
Hello,

> In this case the measured time could lie under the hardcoded 10 seconds and as the result the reply get rejected.

Well, one could see it as another feature, if the _last_ activity is evaluated w.r.t. SPAM protection. Moreover, afaik _nobody_  complain about the current implementation. How often do you notice the 10 sec barrier, if you wrote to the forum?

/Micha

**Comment by auge8472** [comment]
Hehe, I myself was trapped twice or thrice since MLF2 got public (in the project forum) but I can't remember any report about this issue from another side. Yes, it seems to be *very* seldom but it's a possible corner case when one is massively working with browser tabs.

**Comment by loesler** [comment]
Hi,

the current implementation set the reference time on form visiting (and not by any page load). If you trapped into the barrier, you must have open the same form several times. I'm sorry, I cannot reproduce this _massively working with browser tabs_ ;-)

Anyway, I don't like to talk about the threshold. Maybe, we should it declare in the forum settings table (instead of a hard coded threshold). But if we follow my suggestion, you may trapped into the barrier more frequently (depending on the threshold).  

/Micha

**Comment by auge8472** [comment]
> the current implementation set the reference time on form visiting (and not by any page load).

Visiting a form is caused by loading the page that contains the form.

Also anyway, IMHO we should implement it as a function and call it only where necessary (registration, posting, contact form). Additionally I'm not convinced by adding a further forum setting for the minimal time. I suspect misconfigurations caused by experimenting forum admins. :-)

**Comment by loesler** [comment]
Hi,

>  I suspect misconfigurations caused by experimenting forum admins. :-)
Well, following this line of reasoning, _each_ parameter in settings table can be misconfigured.

**Comment by loesler** [comment]
Hej,

I add a first version, i.e. https://github.com/ilosuna/mylittleforum/issues/406. I removed the hard coded thresholds and some new values are added to the setting db table.

/Micha

**Comment by loesler** [comment]
Done by https://github.com/ilosuna/mylittleforum/pull/413
