### ISSUE TITLE
PHP function each() is deprecated

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#409]
During the tests for version 2.4.15 (see #408) I ran into the message, that [the function `each` is deprecated](http://php.net/manual/de/function.each.php) as of PHP version 7.2. There are only seven places, where the function gets called. For all cases except a single one we can preplace the code with a foreach.

~~~ php
# from
while (list($key, $val) = each($foo)) {
# to
foreach ($foo as $key => $val) {
~~~

Only the last occurence in `includes/functions.inc.php`, function `my_quoted_printable_encode` is because of the `list(, $line)` syntax a bit disturbing for me.

~~~ php
while (list(, $line) = each($lines)) {
~~~

Does that mean, that the code reads only the value (`$line`) and ignores the numeric keys of the array elements (in front of the comma)?

If yes, a simple `foreach ($lines as $line)` would be a proper replacement.

**Comment by loesler** [comment]
Hej,

yes, you are right. It is simple `foreach ($lines as $line) { }`. I will replace the deprecated function.

**Comment by loesler** [comment]
Solved by https://github.com/ilosuna/mylittleforum/pull/410
