### ISSUE TITLE
Array of bookmark with entry for tags even there is none

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#417]
I wanted to put the tags of a bookmark into a list in the bookmarks page of my theme and encountered a problem. Even there is no tag (the [query in `bookmark.inc.php`](https://github.com/ilosuna/mylittleforum/blob/3e06e35f1f4c8df25d7781c60a355d73799ea620/includes/bookmark.inc.php#L39) returns `NULL` values for `tag_id` and `tag`) the PHP code builds an array for the Smarty template. That causes the default theme to contain an empty and broken link (the URL-parameter for the tag name is empty) and my theme to build an empty list.

Additionally the query returns a result row for every bookmark with every single tag. A bookmark with three tags will result in three result rows. I want to separate the query for the tags from the query for the bookmarks. Afterwards I can put the result into the array of the bookmarks result.

**Comment by loesler** [comment]
I check the sql result against NULL values. The bug itself is fixed by https://github.com/ilosuna/mylittleforum/pull/419
