### ISSUE TITLE
No UI for a new request for acceptance of data privacy agreement or terms of use

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#425]
After introducing the data privacy statement and the unified handling with the terms of use agreement and especially the new possibility to renew the request for acceptance for the case of changes in (one of) the agreements, we need a UI to invalidate the (then old) agreements of registered users in the admin panel.

Task is technically to delete the timestamps of the acceptance of the data privacy statement (`dps_accepted`) and/or the terms of use (`tou_accepted`) from the user data entries. With this, all users are enforced to accept the new agreement when logging in next time.

**Comment by loesler** [comment]
Your are right. Maybe, we should (also) add some (permanent) link to the data privacy statement, too. Currently, it is not possible to read the statement again, isn't it?

**Comment by loesler** [comment]
> Question is, where to place?

During answering, under each posting (textarea) (but with checked option)?

**Comment by auge8472** [comment]
solved with #430
