### ISSUE TITLE
Make refresh-link behaving comprehensible

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#45]
The use of the refresh link makes every entry unread and removes the info about new entries. Either the link has to act as "mark all unread" or as "mark all read" or it should load new content but leaves the read- and the new-content-status as it is.

The way it works now is _unexpected_ ((not only) for me).

**Comment by derletztekick** [comment]
> The use of the refresh link makes every entry unread and removes the info about new entries.
That's right and confirms the advanced information from the tooltip. If we don't want to change the source code (i.e. main.inc.php, line 264ff), we have to rename the label of the link to "mark all as read". So the question is: What do you prefer?

**Comment by auge8472** [comment]
My observation is, that the refresh link marks all entries ***un***read. All pseudoclasses `a:visited` will be removed and the classes `.new-entrynew` and `replynew` will also be removed. There is no indicator for new entries after using the link.

A link or button, that removes these indicators for new entries, as we have it, is IMHO useless. A link or button to only load new entries is useless too, because the browsers have a few possibilities to handle this. But a link or button, that marks all entries read, would be handy (even it would not be *my* usecase).

**Comment by derletztekick** [comment]
> My observation is, that the refresh link marks all entries unread.

No, the postings are marked as read, if the icon indicates whenever a posting is read or even not.

> the classes .new-entrynew and replynew will also be removed.

And that's why you conclude there were marked as *un*read?

> All pseudoclasses a:visited will be removed

Its a browser behaviour, isn't it?

**Comment by auge8472** [comment]
> And that's why you conclude there were marked as unread?

Yes. This and the fact, that my browser removes the styles for visited links after clicking the refresh-link. 

> > All pseudoclasses a:visited will be removed

> Its a browser behaviour, isn't it?

No, it's not a browser behaviour to remove the pseudo class `:visited` from links by clicking a further link that reloads a page.

**Comment by derletztekick** [comment]
It is a browser issue ;-) because the forum-software has no influence on pseudo-classes like `:visited`. The software doesn't remove anything. Based on the browser history, the pseudo-class is applied or even not.

> reloads a page

The link doesn't just reload the page. The link modified the cookie and reload the page. Maybe, it is a security issue of the browser.

**Comment by auge8472** [comment]
Really? My standard browser Firefox and my other browsers (Vivaldi (Chromium-Engine), IE 11) and [the](http://mylittleforum.net/forum/index.php?id=6542) [other](http://mylittleforum.net/forum/index.php?id=7196) [ones](http://mylittleforum.net/forum/index.php?id=5857) browsers?

The screenshot shows the latest-entries-box before and after clicking the refresh-link. On the left side are the two entries at top of the listing correctly marked as `:visited`. After clicking the refresh-link the styling as a visited link is gone. No, this is not only a browser issue.

![refresh-bug](https://cloud.githubusercontent.com/assets/1734660/19445967/e4e43fac-9496-11e6-9a25-96b528b088a1.png)

**Comment by derletztekick** [comment]
> correctly marked as :visited

By the browser not by the forum and yes, all my installed browsers working in this way, so I can confirm your `observation`. But this is not the point. The point is: The forum software itself doesn't remove or change the pseudo-classes. If you remove the setcookie-function (i.e. main.inc.php, line 264ff). The forum will reloaded in the same way like pressing <F5>. Thus, I believe it is a browser matter for security reasons e.g. javascript can determine the visited pages via pseudo-classes.

**Comment by glorifyday** [comment]
> The point is: The forum software itself doesn't remove or change the pseudo-classes.

Are you sure about this?
I have ben testing how tmlf2_userdata.entries_readis changing as I browse the forum.
As I browse (or ajax-preview) the posts, the lenght of the string in the field gets longer and longer before it reaches 999.
When I click 'Refresh', the field gets nulled.
What is that field for if the forum is not using it to se the unread style?

If I might suggest anything, this mechanizm should be created just the way round: there should be a mlf2_userdata.entries_**un**read field, the code logic should follow its name, and this field should be nulled with 'Refresh'.

The mlf2_userdata.entries_read field should not be nulled with 'Refresh'. This is my intuition.

**Comment by derletztekick** [comment]
Hi,

yes, I'm sure. You (and Auge) are mixing different behaviours. The pseudo-class is interpreted by the browser (and its history). The `mlf2_userdata.entries_read`  is used to change the icon in front of the topic title. The forum software indicates _new threads/postings_ by a red bordered icon, cf. http://mylittleforum.net/forum/themes/default/images/bg_sprite_1.png - neither more nor less.

/Micha

**Comment by glorifyday** [comment]
Strange. My browsing tests showed something different. I'll start a topic on the discussion forum, however, if you don't mind...

**Comment by derletztekick** [comment]
> My browsing tests showed something different.

In which case?

**Comment by glorifyday** [comment]
I started with clickng Refresh, so I ensured there were no new posts.
Then every time I read or ajax-previewed a posting, its id was appended to entries_read. Refreshing with F5 resulted with marking the ajax-previewed postings with read style (purple colour) and it was consistent with the contents of the entries_read field.
Then I clicked the Refresh link again and the field was nulled and all postings became unredad, i.e. blue.
During the test, there were no new postings at the forum. 

Maybe we should continue on the project test forum, what you think?

**Comment by derletztekick** [comment]
Hi,

again, you are mixing to behaviours. The "purple colour" that indicates whenever the page is in the history/cache of *your* browser, is not a css-class or something like that. If you click the "refresh" button, only the icon is changed by the software (but not the colour of the link). The colour of the link (visited/unvisited) is set by your browser depending on its history or cache or something else. If you visited a posting (and it is marked as read by the purple colour, clear your browser cache and your history etc. and you will see, the posting is marked as unvisited (i.e. the link colour ist blue).

/Micha

**Comment by glorifyday** [comment]
Maybe, but how do you explain the fact that purple / blue corresponds exactly to the contents of entries_read?
And one thing more, consider the following scenario:
- I see an unread / blue posting
- I ajax-preview it
- the id of the posting is appended to entries_read but the posting is still blue
- I press F5
- the posting turns purple.
I am a Java/C++ programmer and I find it difficult to read PHP code, so I am not sure how it works, but in this case it seemes obvious that the read style was set on a page reload using the data stored in entries_read field.

P.s. I am using the github on a tablet right now and I think I have missed while tapping this thread here - some icon with "2.4" disappeared. Sorry :-/.

**Comment by derletztekick** [comment]
Hi,

> Maybe, but how do you explain the fact that purple / blue corresponds exactly to the contents of entries_read?

This array is used to change the css-class, i.e. to switch between the icons in front of the topic-title.

> the read style was set on a page reload using the data stored in entries_read field.

No, that's not true. It is not possible to set a pseudo-class to an element.

/Micha

**Comment by auge8472** [comment]
> It is not possible to set a pseudo-class to an element.

But it is possible to remove a class. The purple colour of the visited links does not come from the browser- or the author-stylesheet for `a:visited` but it is setted by the CSS-rule for the class `.read` in `style.min.css` (line 346).

The refresh button triggers the removal of the class from the links to visited entries. The title attribute (at least in the German language) clarifies the purpose of the refresh-link much more, than the name does in itself. It says: "neue und gelesene Einträge zurücksetzen" (my on-the-fly translation: reset new and read entries).

And **that** is counterintuitive.

**Comment by derletztekick** [comment]
Hi,

you wrote:

> All pseudoclasses a:visited will be removed

Thus, I don't verify this issue in detail because a pseudo-class is out of scope of the forum software. But now you are right, there is no pseudo-class definition - and, thus, I'm wrong. ;-)

Thus, to mark all threads as read, we have to extend the `entries_read` -array (instead of clearing). Is it right?

/Micha

**Comment by glorifyday** [comment]
I suggest to store entries_unread instead - there will be less of them in general.

Or a simpler solution: a timestamp field in the user's table, indicating the time up till which the user has read the forum.

**Comment by auge8472** [comment]
> I suggest to store entries_unread instead - there will be less of them in general.

@glorifyday No, I disagree. There are many more unread entries than read ones, if a registration happens long time after the installation. This is IMHO the predominant case. That said, the stored value should be the read status.

> Thus, to mark all threads as read, we have to extend the entries_read -array (instead of clearing). Is it right?

@derletztekick At which point a single entry will be marked as read? If I open it in the browser? If yes, the status should stay unchanged when using the refresh-link. IMHO the refresh link should only reload the page (as it does) **and**, *if an user is logged in (!)*, remove the unread-arrows from the read entries but *not* from actually unread entries.

**Comment by derletztekick** [comment]
> @derletztekick At which point a single entry will be marked as read?

I don't know. But following glorifyday: If the posting is given in `entries_read`-array. 

> IMHO the refresh link should only reload the page

Edit [main.inc.php#L264](https://github.com/ilosuna/mylittleforum/blob/master/includes/main.inc.php#L264) and remove 

```
$_SESSION[$settings['session_prefix'].'usersettings']['read'] = array();
setcookie($settings['session_prefix'].'read','',0);
```

**Comment by glorifyday** [comment]
When there are too many unread posts, most users don't want to read them all. They want to 'mark all as read' and start over again.

Keping information of all the read posts seems imposible for me. This will be growin without limits. If you lmit it for pracical reasons, then you will have to implement inelegant workaounds for the old postings.

This was dicussed on the project forum. I described my suggestions in detail there.

**Comment by auge8472** [comment]
> When there are too many unread posts, most users don't want to read them all.

That's most likely true.

> They want to 'mark all as read' and start over again.

Then they should do this. With a button –or more general an element– named 'mark all as read'.

> Keping information of all the read posts seems imposible for me. This will be growin without limits.

Come on. [The largest MLF forum I found on the quick](http://forum.bebac.at/mix.php) (a MLF**1** driven forum) has a bit more than 16,000 entries in around 3,500 threads, written by nearly 1,000 registered users and an unknown number of unregisterd users.

The information about read entries will only be stored for registered users. Even if *every single entry* is marked as read *for every single user* –and this is typically not the case because users come and users goes– this would be an amount of only 160,000 datasets with the ID of every single posting and the ID of every single user (in a more appropriate structure).

>  If you lmit it for pracical reasons, then you will have to implement inelegant workaounds for the old postings.

For forums with an automatted locking of old threads (comparable with an archive) the info about read entries can be removed for these old threads. That should limit the storing size of the database table.

**Comment by glorifyday** [comment]
OK, if you are ready to keep this info without limits, it's possible. Maybe it's a good solution. Then the info should be in a separate table, related to user data.
Anyway, I am not an enthusiast of the automated locking of old threads. It might be an optional behaviour of the forum, though.

When we last discussed the matter, you mentioned the limit of 300 posts remembered (for a user) as read.

Under such condition, if this number is limited, I suggested that the forum should remember the newest unread posts, not the read ones. In such a solution, very old posts are automatically treated as read.

I don't know which solution you choose, but I would like to ask one more question. What is the logic behind the 'new' postings / threads? The ones with red arrows / red-bordered icons. How is this information stored? I couldn't find this in a code.

**Comment by glorifyday** [comment]
A fast, wild idea:
maybe it's possible to make it working reasonably under current model with just slight changes?

The draft of an algorithm is as follows:
- the forum renders all posts mentioned in entries_read as read
- the forum remembers the timestamp of oldest post mentioned in entries_read
- all the other posts (not mentioned in entries_read) are rendered as read iif they are no newer than the remembered timestamp
- the 'Refresh' link does not nullify the entries_read.

What do you think?

**Comment by auge8472** [comment]
> OK, if you are ready to keep this info without limits, it's possible. Maybe it's a good solution. Then the info should be in a separate table, related to user data.

Yes.

> I am not an enthusiast of the automated locking of old threads. It might be an optional behaviour of the forum, though.

It **is** optional and has to be activated in the settings. On the other hand it is on the administrator to activate the automatted locking of old threads.

> When we last discussed the matter, you mentioned the limit of 300 posts remembered (for a user) as read.

Actually it's the *standard behaviour* to store the last 200 read entries.

> currently, when you store a limited number of read entries, old posts are automatically treated as unread and this is a misbehaviour

Who remembers **very old** entries? We can discuss to use a time (i.e. older than one year) or a number (i.e. 200 or 500 entries) as the limit. But, normally no one cares about this old entries. If one find and read an old entry, it's on the software to decide, if the entry should be stored as read or not. The browser has it's own list of visited pages as fallback. We must only use the pseudo class `:visited` to style the links and that's it.

> What is the logic behind the 'new' postings / threads? The ones with red arrows / red-bordered icons. How is this information stored? I couldn't find this in a code.

The base of this information is stored in the cookie with the time of your last visit. All entries that have newer timestamps are marked as unread/new and gets the red arrows and/or red bordered icons.

**Comment by auge8472** [comment]
grml

Clicked wrong button. Reopen it now.

**Comment by glorifyday** [comment]
Do you think we should continue our discussion here or maybe create a dedicated thread on the project's test forum?

**Comment by auge8472** [comment]
I think Milo and I should begin with the work instead discussing around the issue. I will open a first PR with the CSS-rules to correct the looks-like-it's-marked-as-unread-after-clicking-the-refresh-link-misbehaviour and a second one with the CREATE-statements for the database table (in the install- and update-stripts). At that point we will have a base for further discussions.

**Comment by glorifyday** [comment]
Having a plan before you start actual coding wouldn't be an obstacle, anyway ;-).

Actually, in this discussion, the following solutions were suggested:
1. refactoring entries_read to a new table related to user data and removing the limit of read entries per user (read entries in locked threads would not be kept)
2. keeping the current model with the workaround that I described yesterday ("fast, wild idea")
3. keeping the limit, but entries_read refactored to entries_**un**read (the field would maintain, say, 200 newest unread posts, all other posts would be rendered as read)
4. user timestamp(s) approach: a collection of timestamps is kept per user - one for each category and one category-less; they are used depending on a selected category; the posts not newer than the timestamp are rendered read; a 'Mark all read' link is introduced - when a user clicks the link, his timestamp advances to the time when the user last reloaded the webpage.

I suspect that:
- 1 and 4 are the most complete solutions
- 2 and 4 mean least of work
- 1 means storing most data
- 4 means storing least data

Do you tend to implement solution 1?

**Comment by auge8472** [comment]
> Do you tend to implement solution 1?

Yes.

> I think that rendering posts as read/unread should not rely on pseudoclasses.

Why? It's always the case since browsers marked the links to visited pages with a different colour than unvisited. The only limit is, that this techique is restricted to the single browser.

> The user should have a clear overview of what (s)he read or marked as read …

That#s the case with the browsers pseudo class …

> … and this information should be kept by the forum engine.

… and with the forum dependant data too.

**Comment by glorifyday** [comment]
> That#s the case with the browsers pseudo class …

No, because this information will be lost:
- on another browser
- on another machine
- when the user clears browser data for some reason

I think that the overview of read/unread posts should be user and forum related and should not depend on browser state.

**Comment by auge8472** [comment]
> > That's the case with the browsers pseudo class …
> No, because this information will be lost:

And? Nothing new? That's the basic.

> I think that the overview of read/unread posts should be user and forum related and should not depend on a browser state.

I don't find the place, where I contradicted your words. :confused:

**Comment by glorifyday** [comment]
Never mind, maybe I misunderstood something. 
As long as you intend to render read/unread state basing on forum database and separate this behaviour from browser-maintained state, I am perfectly satisfied and I believe most users will.
Thanks.
