### ISSUE TITLE
Restrict the access to the users list to the admins and moderators

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#457]
In the project forum a user proposed the possibility of a stronger restriction for the access to the user list. Currently we have the setting `user_area_public` with possible values of `0` (restricting the access to only registered users or `1` with access also for unregistered visitors. Because of the name and value sequence it would be a candidate for renaming and new order of values.

My proposal is to rename it to `user_area_access` with the following possible values: `0` (no restriction), `1` (only registered users) and `2` (only team members (mods and admins)).

**Comment by loesler** [comment]
Sounds reasonable. Can you add the necessary changes?

**Comment by auge8472** [comment]
Yes I will implement it and request a review.

**Comment by auge8472** [comment]
> My proposal is to rename it to `user_area_access` with the following possible values: `0` (no restriction), `1` (only registered users) and `2` (only team members (mods and admins)).

Because this is a security relevant setting, we should IMHO invert the values for access for only team mebers (should be `0` and should also be the default value) and unlmited access (shoudl be `2`). With a broken update function or settings array there would be an error message or the script would use the strictest possible value (`0`) as the default. This would prevent user data being uncloaked unintended.

**Comment by auge8472** [comment]
@loesler Why did you assign me to the issue? Did you mix it up with the corresponding pull request (#470)?

**Comment by loesler** [comment]
You are the one, that works on this topic.

**Comment by auge8472** [comment]
I mixed up the review and the assignment.

**Comment by auge8472** [comment]
After merging #470 the issue is solved. I'll closing it now.
