### ISSUE TITLE
Email to users only for registered users

### ISSUE THREAD

**Issue by HolgerJeromin** [ilosuna/mylittleforum#465]
A spammer found our forum to send emails at least to me.
I have configured that I can receive emails throughout the forum. 

I am surprised that the page is linked with the icon and working even for unregistered users:
/forum/index.php?mode=contact&id=42
![image](https://user-images.githubusercontent.com/2410353/52918503-2543f680-32f8-11e9-8a4f-1f9c398a91ae.png)

Is this a bug/missing feature in my old version 2.3.4 or even in the latest release?

**Comment by auge8472** [comment]
This is neither a bug nor a missing feature in general. It is an intended feature to make users contactable if they gave their permission. But you are right, it should be possible to restrict the access to the feature to registered users only, *at least* if only registered users are allowed to write entries.

If the access to the forum itself is restricted to registered users, the problem does not exist.

**Comment by loesler** [comment]
Done by https://github.com/ilosuna/mylittleforum/pull/505
