### ISSUE TITLE
link to apply the quote to the posting textarea disappears when posting page reloads

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#474]
During some tests I came across a bug in the posting(.min).js. When I loaded the posting form page the link to quote the message came up but when I **re**loaded the form page, the link disappeared. The relevant code resides in posting.js, beginning with [line 700](https://github.com/ilosuna/mylittleforum/blob/master/js/posting.js#L700). I suspect the check `textarea.getQuote() != ""` to fail but I am not sure about it.

Beside of that I have a few concerns about the way the function is designed.

1. Because the quote-message-function is pure JS that will work inside the page without the possibility of a reload, a button instead the link is the appropriate element.
2. The link (or the button) is an interactive element but the enclosing label is an interactive element in itself. Because of that, the link (or button) *must not* be a child of the label.

But that's another story.

**Comment by loesler** [comment]
I'm wondering, that you call it bug even if nothing went wrong or is broken. If I reload the form page (via <F5>), the link is _displayed_.

> a button instead the link is the appropriate element.
Why? I cannot follow your argumentation. JS functions are not limited to buttons or other elements. And as already mentioned, if I reload the page, the link is _displayed_.

> the link (or button) must not be a child of the label.
W3C or which organization recommends it this way?

**Comment by auge8472** [comment]
> I'm wondering, that you call it bug even if nothing went wrong or is broken. If I reload the form page (via F5), the link is *displayed*.

Hmm, when I use F5 *or* the reload button in Firefox, the link disappears with the reload. In Vivaldi (Chromium engine) the link is visible after a reload (F5 *and* reload button). So it is to state, that the behaviour is broken at least in Firefox.

> > a button instead the link is the appropriate element.
> 
> Why? I cannot follow your argumentation.

- `a`: If the `a` element has an href attribute, then it represents a hyperlink (a hypertext anchor) labeled by its contents. If not, then the element represents a placeholder for where a link might otherwise have been placed, if it had been relevant, consisting of just the element’s contents.
- `button`: The `button` element represents a control allowing a user to trigger actions, when enabled. It is labeled by its content.

If one clicks "quote message", it should take an action inside the page (what a button of type "button" is for) without loading another page or jump to another section of the same page (what a link (a) is for) or whatever. A link is something, one (or more exact: the client) can *follow*, a button (of type "button") triggers an immediate action without the need to follow to somewhere.

This is more a generally question about the purpose of individual HTML elements and not about JS. We could also have a `div` to insert the quoted message instead an `a` (or a `button`) and make it interactive with JS but we use a per se interactive element. The element `a` is *IMHO* a valid but not *the best* choice for this purpose. Anyway ...

> > the link (or button) must not be a child of the label.
> 
> W3C or which organization recommends it this way?

Ok, W3C allows `a` in `label` in HTML5 (see [example 4 for label](https://www.w3.org/TR/html5/forms.html#the-label-element)) but it explicitely does not recommend it (see the comment in the code of example 4). So I have to rephrase to "the link *should* not be a child of the label". Obviously I was mistaken because of `a` and `button` (and some [other interactive elements](https://www.w3.org/TR/html5/dom.html#interactive-content-2), where the rule "no other interactive content inside one of these elements" still applies.

What remains is the problem with the (or my?) Firefox.

**Comment by loesler** [comment]
> If one clicks "quote message", it should take an action inside the page (what a button of type "button" is for) without loading another page

Pressing a submit-button, a new page is loaded. The action of a button is not restricted to "inside the page" modifications. 

> What remains is the problem with the (or my?) Firefox.

Is it really a problem, i.e., how often you are clicking F5... and the more important question: why??? For me, it sounds like a hard constructed "problem".

**Comment by auge8472** [comment]
> > If one clicks "quote message", it should take an action inside the page (what a button of type "button" is for) without loading another page
> 
> Pressing a submit-button, a new page is loaded. The action of a button is not restricted to "inside the page" modifications.

Sorry, but why do you think, I added the half sentence about button of type "button" inside the brackets? Yes, a `<button>` is a submit button but a `<button type="button">` is a page-internal action button.

> how often you are clicking F5... and the more important question: why??? For me, it sounds like a hard constructed "problem".

Yes, it is more or less constructed because I was trapped *for the very first time* during tests of exactly this function (the function does not work in my theme). I tested it in the MLF-project-forum as well as in my own forum for comparision. And so I reloaded the posting form again and again, viewing the browser console window, and somewhen I noticed the absence of the link. So it is in reality a very rare edge case but it exists and thatswhy I wanted to report it.

Because of the very low likelyhood of the case I close the ticket with "wontfix".

**Comment by loesler** [comment]
I can change the element, no problem. Which element is the parent of the button?What do you prefer?

**Comment by auge8472** [comment]
Thank you for your regard. The link is currently a child of the label for the textarea (query selector: `fieldset#message label.textarea a`).

~~~
<label class="textarea" for="text">Message: <a>quote message</a></label>
~~~

 **\*btw\*** At that point I became aware that the link has a `href` (index.php?mode=posting&amp;id=[0000]&amp;back=entry). I thought, ok, maybe this link is the non-JS-version of the quote-message-function. But it isn't. The URL, when requested, loaded the empty posting form for a new topic and not for a new reply with the posting text. Very crude and additionally useless, because with no available JS the posting content remains visible when loading the reply form but the quote-message-link doesn#t get created.

Back to topic.

*IMHO* the link or (*IMHO* better) the button should be the labels neigbour (query selector: `fieldset#message label.textarea + button`).

~~~
<label class="textarea" for="text">Message: </label><button type="button">quote message</button>
~~~

Is that maintainable in an easy manner?

**Comment by loesler** [comment]
> this link is the non-JS-version of the quote-message-function

Since the link is added by JS, there isn't a non-JS version by nature. ;-)

> Is that maintainable in an easy manner?

If it is a better - lets say - style of code, I will try to change the JS sources. So, your task will be the related styling of the button by css. Deal?

**Comment by auge8472** [comment]
Deal :-)

**Comment by loesler** [comment]
I replaced the link by a button an insert the new button _behind_ the label, cf. https://github.com/ilosuna/mylittleforum/pull/475

`<input type="button" id="insert-quote" value="quote message" title="Insert quoted text of the posting to be replied on" tabindex="-1">`

I transfer the id of the link to the button. For styling, `#insert-quote` is available.

**Comment by auge8472** [comment]
Thank you. I'll add the styling after the answer to the following question.

Until now we do not style buttons but let the browser use the styling of the operating system. I inserted the button as you defined it with the browser development tools of Firefox in Windows 10 and Ubuntu Mate desktop environment and removed the padding and the background image with the double quotes (looked very ugly because of `background` setting unwanted defaults for more than the background image). That's the outcome of the *draft* (first image Windows, second one Ubuntu with Mate):

![MLF2 unstyled button in Windows 10](https://user-images.githubusercontent.com/1734660/58245241-a1653480-7d54-11e9-806f-aa285b44bb7d.png)

![MLF2 unstyled button in Ubuntu 16.04 with Mate desktop](https://user-images.githubusercontent.com/1734660/58245339-da050e00-7d54-11e9-94f5-6a0cd7a9313d.png)

Should we start to style the forum more modern with this button or should we follow the hitherto existing styling (guide) and let the browser and the  OS do the work? As a third option I can make the button look like the link that is used until now (as you can see in the following screenshot).

![MLF2 button styled as a link in Windows 10](https://user-images.githubusercontent.com/1734660/58246786-46354100-7d58-11e9-93d0-5b4fdd8082eb.png)

**Comment by loesler** [comment]
> As a third option I can make the button look like the link

To avoid confusions by the users (after the forum update), I prefer this option, yes.

**Comment by auge8472** [comment]
> > As a third option I can make the button look like the link
> 
> To avoid confusions by the users (after the forum update), I prefer this option, yes.

I'll do so. :-)
