### ISSUE TITLE
SQL error installing 2.4.99.1

### ISSUE THREAD

**Issue by guzzisti** [ilosuna/mylittleforum#482]
hi,

i've tried to do a clean install of 2.4.99 for testing purposes. My host is running PHP7.3 and MySQL 5.7. The installation fails with the following sql error:
```
'Fehler!'
    'SQL-Fehler' (MySQL: COLLATION 'utf8_bin' is not valid for CHARACTER SET 'utf8mb4')
    'SQL-Fehler' (MySQL: Table 'd02ea71d.mlf2_b8_wordlist' doesn't exist)
```
Having a look at the database, there's a wild mix of engines and collations:
![image](https://user-images.githubusercontent.com/10488791/58829494-3e26ac80-8648-11e9-8cc4-f9795dd6f531.png)

I may be able to provide a PR tomorrow which fixes the db schema.

**Comment by loesler** [comment]
Hi,

please change the [following line](https://github.com/ilosuna/mylittleforum/blob/master/install/install.sql#L23) in install.sql from

``CREATE TABLE mlf2_b8_wordlist (`token` varchar(255) character set utf8mb4 collate utf8_bin NOT NULL, `count_ham` int unsigned default NULL, `count_spam` int unsigned default NULL, PRIMARY KEY (`token`)) CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;``

to

``CREATE TABLE mlf2_b8_wordlist (`token` varchar(255) NOT NULL, `count_ham` int unsigned default NULL, `count_spam` int unsigned default NULL, PRIMARY KEY (`token`)) CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;``

/Micha

**Comment by auge8472** [comment]
> Having a look at the database, there's a wild mix of engines and collations:

For clarification: It's intended that some of the tables stay UTF8 (3 byte) and others got the fourth byte. It's also intended that a few columns get *not* the collation `utf8_general_ci` respective `utf8mb4_general_ci` but get the collation `utf8_bin` respective `utf8mb4_bin` instead. That said, Michas solution isn't correct. I will request changes for the pull request in the next few minutes.

**Comment by guzzisti** [comment]
Thanks for clearing things up. Is the storage engine mix also intended?

**Comment by loesler** [comment]
It is correct that we have the construct:

``varchar(255) character set utf8mb4 collate utf8mb4_general_ci``

only one times?

**Comment by auge8472** [comment]
If the table is in general defined as …

~~~
CREATE TABLE mlf2_foo () CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
~~~

… all text fields in the table are defined similar. If a single field should have a different collation you have to specify it and you have ta say, that the table defaults are only a `DEFAULT` but can be overruled. We have only two cases, the field `mlf2_userdata.user_name` and, what I broke, `mlf2_b8_wordlist.token`.

~~~
CREATE TABLE mlf2_foo (
  bar varchar(255) character set utf8mb4 collate utf8mb4_general_ci
) CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_general_ci;
~~~

**Comment by loesler** [comment]
> If a single field should have a different collation you have to specify it

Okay, and why do you set this option for `mlf2_b8_wordlist`? The table has three columns, `varchar`, `int`, `int`.

**Comment by auge8472** [comment]
Okay, and why do you set this option for mlf2_b8_wordlist? The table has three columns, `varchar`, `int`, `int`.

The table was defined before my UTF8-related changes as:

~~~
CREATE TABLE `mlf2_b8_wordlist` (
 `token` varchar(255) character set utf8 collate utf8_bin NOT NULL,
 `count_ham` int unsigned default NULL,
 `count_spam` int unsigned default NULL,
 PRIMARY KEY (`token`)
) CHARSET=utf8 COLLATE=utf8_general_ci;
~~~

The use of the collation `utf8_bin` for `token` is IMHO intended because there is the same issue as we had once with the uniqueness of the user names (i.e. "Änni" versus "Anni"). Because of that I simply replaced "utf8" with "utf8mb4". But i forgot to change the collation of the column `token` in the installation script what led us to this bug report.

**Comment by loesler** [comment]
> edit I think we can simplify the create statement

...this was my intension. ;-)
