### ISSUE TITLE
B8 definition

### ISSUE THREAD

**Issue by loesler** [ilosuna/mylittleforum#492]
We added the Bayes based filter B8 to check the forum [entries](https://github.com/ilosuna/mylittleforum/blob/master/includes/posting.inc.php#L7) and the [emails](https://github.com/ilosuna/mylittleforum/blob/master/includes/contact.inc.php#L7). Currently, the definitions are redundantly (i.e. in both files). I think, we should move the definitions to a more central place e.g. to the index.php (or an unique  configuration file). Any suggestions?

**Comment by auge8472** [comment]
Wenn es keinen Grund dafür geben sollte, in beiden Fällen unterschiedliche Einstellungen zu verwenden (wonach es nicht aussieht), sehe ich keinen Grund, den Code nicht in ein per `include` oder `require` zu ladendes Skript auszulagern. Und selbst dann sollte sich das mit einem `if`-`else`-Block innerhalb dieses Skripts regeln lassen.

**Comment by loesler** [comment]
Okay, following your suggestion, I will create a b8_config file.

**Comment by loesler** [comment]
Done by https://github.com/ilosuna/mylittleforum/pull/493
