### ISSUE TITLE
Site settings are not saved after update to 2.4.20

### ISSUE THREAD

**Issue by adfcwebmaster** [ilosuna/mylittleforum#513]
After I updated from 2.4.13 to 2.4.20 saving the site settings does not set the data in the settings table.
I edit some settings in Admin -> Settings an click OK. I'm back in the main administration view  without any error messages. Reopening settings form just changed item is back to former value. In database table are no changes visible.

Webdebug mode shows sent data (snippet: {"Formulardaten":{"mode":"admin",...,"settings_submit":"OK+-+Einstellungen+speichern"}}).

Changing user data works!

PHP 7.2.19, mysql 5.7.26 (Ubuntu)
Firefox (70.0) Windows 10

How to fix? How to debug?

Thanks

**Comment by auge8472** [comment]
It's a bit guess working but I suspect a not actualised template or script file. It smells like a nonexisting CSRF-token-field in the settings form and that would be a case of forgotten upload of a new file version.

In a first attempt, please reupload the files [includes/admin.inc.php](https://github.com/ilosuna/mylittleforum/blob/2.4.20/includes/admin.inc.php) and [themes/default/subtemplates/admin.inc.tpl](https://github.com/ilosuna/mylittleforum/blob/2.4.20/themes/default/subtemplates/admin.inc.tpl) and try again.

**Comment by adfcwebmaster** [comment]
> It's a bit guess working but I suspect a not actualised template or script file. It smells like a nonexisting CSRF-token-field in the settings form and that would be a case of forgotten upload of a new file version.
...
There is indeed not csrf field in the form an as consequence no csrf data sent.
...
> In a first attempt, please reupload the files [includes/admin.inc.php](https://github.com/ilosuna/mylittleforum/blob/2.4.20/includes/admin.inc.php) and [themes/default/subtemplates/admin.inc.tpl](https://github.com/ilosuna/mylittleforum/blob/2.4.20/themes/default/subtemplates/admin.inc.tpl) and try again.
...
I made shure I have those files in up to date version.  In both files on my server there is csrf handling resp. csrf field but still no csrf field in the form received in the browser. It seems as if the form is somewhere cached. I cleared browser cache and templates_c dir.

There was a directory "templates" on the server which is not existing in git. I deleted it on the server, cleared the caches but still no luck.

**Comment by adfcwebmaster** [comment]
It is strange: In the smarty generated cachet template of admin.inc.tpl there is NO csrf line at least for 'settings' but in the admin.inc.tpl there is! It seems as if smarty eliminates the line.

Cached admin.inc.tpl snippet:

```php
<?php if ($_smarty_tpl->tpl_vars['action']->value == 'settings') {
if ($_smarty_tpl->tpl_vars['saved']->value) {?><p class="ok"><?php echo $_smarty_tpl->smarty->ext->configLoad->_getConfigVariable($_smarty_tpl, 'settings_saved');?>
</p><?php }?>
<form id="settings" action="index.php" method="post" accept-charset="<?php echo $_smarty_tpl->smarty->ext->configLoad->_getConfigVariable($_smarty_tpl, 'charset');?>
">
<div>
<input type="hidden" name="mode" value="admin" />
<table class="normaltab" border="0" cellpadding="5" cellspacing="1">
```

Original admin.inc.tpl:

```php
{if $action=='settings'}
{if $saved}<p class="ok">{#settings_saved#}</p>{/if}
<form id="settings" action="index.php" method="post" accept-charset="{#charset#}">
<div>
<input type="hidden" name="mode" value="admin" />
<input type="hidden" name="csrf_token" value="{$CSRF_TOKEN}" />
<table class="normaltab" border="0" cellpadding="5" cellspacing="1">
```

What about this?

**Comment by auge8472** [comment]
Do you use the default theme or did you create your own (maybe until now not acualised) theme?

**Comment by adfcwebmaster** [comment]
> 
> 
> Do you use the default theme or did you create your own (maybe until now not acualised) theme?

I use the newly uploaded default theme.

I'm now playing with the smarty console. In the Smarty object template variables `$edSet` **and**  `$settings` are **no** csrf properties whatsoever. But there **is** a variable `$CSRF_TOKEN` with a plausible value.

PS: Adding a category does not work too.

**Comment by auge8472** [comment]
Possibly there is a constraint for generating the token in the HTML source. I'll look into it later (no time now).

**Comment by loesler** [comment]
Do you clearing the templates_c directory after uploading the new tpl-files?

**Comment by auge8472** [comment]
@adfcwebmaster This issue is nearly one year old. Did you solve your problem with the missed form field?

I'll close this issue for now. If this problem remain to exist feel free to reopen the issue.
