### ISSUE TITLE
How should I name PT-BR lang file?

### ISSUE THREAD

**Issue by leandroramos** [ilosuna/mylittleforum#517]
I am about to translate the forum to pt-br (Brazilian Portuguese). How should I name the file?
brazilian-portuguese
brazilian_portuguese
portuguese-brazil
portuguese_brazil

Thank you.

**Comment by auge8472** [comment]
> I am about to translate the forum to pt-br (Brazilian Portuguese). How should I name the file?

You call it "Brazilian Portuguese" yourself. In the light of the common use of the underscore char in projects file names in combination with the languages name "Brazilian Portuguese" the file name "brazilian_portuguese.lang" seems to be appropriate.

**Comment by leandroramos** [comment]
Thank you :smiley:
