### ISSUE TITLE
Users can't sign up

### ISSUE THREAD

**Issue by WhirI** [ilosuna/mylittleforum#529]
When people try to sign up it says email not valid even though the email is real please help.

**Comment by auge8472** [comment]
Which version of the forum and which PHP-version are you using? To make a guess it is PHP-version 7.3 (or higher) and MLF in version up to 2.4.21?

**Comment by WhirI** [comment]
I use a website hoster called infinity free the my little forum version i use is 2.4.20

**Comment by auge8472** [comment]
The not provided feedback makes me assume, that the problem was gone with the recommended upgrade to the version 2.4.21 (or newer). Because of that I'll close the issue.

Whirl, if the problem continues to exist, please reopen the ticket.
