### ISSUE TITLE
Language files

### ISSUE THREAD

**Issue by derletztekick** [ilosuna/mylittleforum#53]
I believe, we have to add _new_ content to all **available language files** at least in English. If a user select   a specific language and the phrase is missing, no text/message will displayed.

ToDo: https://github.com/ilosuna/mylittleforum/issues/32, https://github.com/ilosuna/mylittleforum/issues/51, https://github.com/ilosuna/mylittleforum/pull/56

**Comment by auge8472** [comment]
In mlf1 I added a request for the english language file before the language file, that is specified in the forum or users setting, will be requested. So the (complete (!)) array of english strings is loaded and all elements, that are present in the later requested translation will rewrite the english strings. The untranslated english strings will remain.

**Comment by derletztekick** [comment]
Okay, a fall-back layer. But this isn't given in version 2 - as far as I know. Can you confirm?

**Comment by auge8472** [comment]
No, it's not (as far as I know).

**Comment by auge8472** [comment]
After adding all the new stuff to every single language file (see #68), I tend to close this issue. Opinions?

**Comment by derletztekick** [comment]
Done!
