### ISSUE TITLE
Lack of information about user type in the thread tree below a single entry

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#535]
The thread trees in the main view as well as the headers of entries in single entry view and threaded views are enriched with the information about the user type (in title-attribute and with class names `registered_user`, `mod` and `admin`). During my researches for an issue in my theme (auge8472/mlf2-themes#19) I found the one place, where the info gets not added because it gets not requested in [the matching database statement](https://github.com/ilosuna/mylittleforum/blob/ffbea1564ec76587e37acac1d33da519729c107c/includes/entry.inc.php#L140) and afterwards not used [in the template](https://github.com/ilosuna/mylittleforum/blob/ffbea1564ec76587e37acac1d33da519729c107c/themes/default/subtemplates/entry.inc.tpl#L77).

I successfully tested a solution with only a change in the SQL-query in my forum, where the theme was already prepared for using the info. I'll provide the fix (with the enhanced template) here too.

**Comment by loesler** [comment]
Good work!
