### ISSUE TITLE
Email on registration

### ISSUE THREAD

**Issue by loesler** [ilosuna/mylittleforum#564]
Can someone confirm that the email is empty, if an admin activate a registered account?

Setting: Users must confirm the creation of an account by clinking the link in an email

1. Create a new account
2. Do NOT click on the link in the email to confirm the registration
3. Log-in as admin
4. Go to Admin --> User area
5. Active the user manually
6. An email is sent to the new user but this mail is empty (in my case)

/Micha

**Comment by auge8472** [comment]
1. Create a new account: **done**
2. Do NOT click on the link in the email to confirm the registration: **done** (in a second attempt, first time I was ignoring the *NOT*)
3. Log-in as admin: **done**
4. Go to Admin --> User area: **done**
5. Active the user manually: **done**
6. An email is sent to the new user but this mail is empty (in my case): ***none!***

I didn't get the e-mail in the sixth step after five minutes. Tested with MLF 2.4.99.3. :-/

**Comment by loesler** [comment]
Are you [sure](https://github.com/ilosuna/mylittleforum/blob/master/includes/admin.inc.php#L723)? How the user is informed that the account is now available in your case?

**Comment by loesler** [comment]
I found the reason. The lang file ist not loaded for `emails`, i.e.,

```
$smarty->configLoad($settings['language_file'], 'emails');
$lang = $smarty->getConfigVars();
```

is missing. I will fix it

**Comment by loesler** [comment]
Fixed!
