### ISSUE TITLE
Install script does not save any setting to the database

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#60]
After installation I saw, that the CSS- and JS-files was not loaded. After a first sight into the HTML-source-code it was clear, that the paths was wrong (i.e. `/themes/default/style.min.css` instead `http://example.com/forum/themes/default/style.min.css`). The settings one can enter into the install script and that should be written into the database did not exist in the settings page. The database connection data, that are written into a file, still existed. The data of the admin was also not written to the database table. Instead a placeholding user named "admin" was created. But the name, that is displayed in the users menu is the one, I entered into the form field. If I cklick the link with my name in the users menu, I land on the profile-edit-page of "admin".

After reentering the data in the settings form and sending the form data to the server, the data was saved.

Can anybody confirm my observance in an own, fresh installation?

**Comment by derletztekick** [comment]
Which version do you use; the current stable or the further release?

**Comment by auge8472** [comment]
I tested the current status of the master branch.

**Comment by derletztekick** [comment]
Confirmed, I commit a fix, cf. https://github.com/ilosuna/mylittleforum/pull/61

**Comment by auge8472** [comment]
Thank you, will test it tomorrow. :-)
