### ISSUE TITLE
invalid UTF-8 string in preg_match()

### ISSUE THREAD

**Issue by derletztekick** [ilosuna/mylittleforum#63]
Hi,

on my local installation, I get the warning: _Warning: preg_match(): Compilation failed: invalid UTF-8 string at offset 13 in functions.inc.php on line 2667_ if I try to register a new user. This warning causes of the modification https://github.com/ilosuna/mylittleforum/pull/54

Can someone confirm this issue?

/Micha

**Comment by auge8472** [comment]
I can't confirm it at the moment because I couldn't test it uintil now. What was the input that broke the script? This is the code in its current status (excerpt):

~~~php
preg_match("/(\x{200b})/u", $string)
~~~

I tested the pattern on regex101.com (needed 20 minutes to find the zwsp-char) and it matched `Tes​ter` (copy it if necessary, there's a zwsp-char between "s" and "t" inside).

**Comment by derletztekick** [comment]
I used this [online tool](https://de.functions-online.com/preg_match.html) to verify the expression but I never checked the changes in mlf. Today, I take a look to issue https://github.com/ilosuna/mylittleforum/issues/62: I registered a user on my local installation and get this warning. The user-name was simple "user". Thus, no special-character is presented?!

The current implementation is: `preg_match("/([[:cntrl:]]|\255)/u", $string)`. 

My local installation should run in UTF-8 (I found the header call). So, I'm not sure, why this warning arises. What is wrong with the `order`-parameter (this parameter is not set and default value is `order = 0`)? You've got me stumped at the moment... :-(

**Comment by derletztekick** [comment]
If I remove the \255, i.e.

`if(preg_match("/([[:cntrl:]])/u", $string)) return true;`

it works. Again, what is \255 doing and what is happens, if the user change from UTF-8 to _what-ever_ in lang-file?

**Comment by auge8472** [comment]
> what is `\255` doing?

I tested again on [regex101.com](https://regex101.com/). Inserting `([[:cntrl:]]|\255)` into the field "Regular Expression", the explanation in the sidebar tells me, that `\255` matches the single character at that code point. Assuming, that ASCII is part of UTF-8 and that the code points in this sector are identic, `\255` is the char "soft hyphen" (see [ascii-code.com](http://www.ascii-code.com/), code point: decimal 173, octal 255). 

With `preg_match("/([[:cntrl:]]|\255)/u", $string).` you wants to match an input string against control characters (with `[[:cntrl:]]`) **or** (with `|`) against the soft hyphen (with `\255`). My experience with regexes is too low to tell you, what's going wrong.

**Comment by auge8472** [comment]
Mir schwant was!

I suppose, that the new included modifier `/u` raises the problem and that it has something to do with the [unicode character properties](https://secure.php.net/manual/en/regexp.reference.unicode.php) that was mentioned in the last passage [of this thread](https://forum.selfhtml.org/self/2016/oct/19/regulaerer-ausdruck-mit-cntrl-erfasst-chinesische-zeichen/1677397#m1677397).

**Comment by derletztekick** [comment]
I follow your suggestion and add `\p{Cf}` in https://github.com/ilosuna/mylittleforum/pull/65

Done!
