### ISSUE TITLE
No hand cursor when hovering buttons

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#639]
When hovering over buttons, the cursor should be displayed as hand, like when hovering over links. This might be especially an issue of the HTML-element `button`.

**Comment by loesler** [comment]
I think, this is not a bug, it is the normal behaviour of the button element.

**Comment by auge8472** [comment]
You are right. The cursor over buttons is, what the browser manufacturers decide. *But* in the meaning of accessibility it is *IMHO* a bad decision, to display the mouse cursor as the "normal" arrow and to show the interactivity of the button *only* with the colour change during hovering.

For signalling links there is the rule of showing it with more than one CSS-"feature". Showing a link not only with a different text colour than plain text but also with an underline and/or with a background (colour) is common for developers who want make websites to include all audience (as far as possible). It's (meanwhile) also common practice to show the interactivitiy of HTML-elements `label` with another cursor pointer and in some cases a changing background when focussed or hovered.

So why not also showing the interactivitiy of buttons with more than one CSS-"feature"? Moreover it's a simple task to add `cursor: pointer;` for `button` as well as `input[type="submit"]` and `input[type="reset"]` (until their complete replacement with `button` everywhere).

**Comment by loesler** [comment]
> So why not also showing the interactivitiy of buttons with more than one CSS-"feature"?

There is no reason, not to style any HTML element, and I have no problem to add the `pointer` property. However, styling cannot be classified in right and wrong. Thus, I wonder that you label this issue as *bug*.

**Comment by auge8472** [comment]
> Thus, I wonder that you label this issue as *bug*.

IMHO it is a usability bug, but it is not a *bug* in itself (in the meaning of an error). I removed the tag *bug* and added *frontend* instead.
