### ISSUE TITLE
Security issue with displaying the content of the password field

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#644]
To display the text content of a password field we change the type of the input element from `password` to `text`. This makes it possible, that the Chrome browser sends the content of this input field to Google for spell checkíng and for resulting proposals. This may be wanted for any text content but not for passwords in any case.

The solution should be to add the attributes `spellcheck="false"` and `autocomplete="off"` (if necessary) to the password fields.

See therefore [a thread in the SelfHTML-forum](https://forum.selfhtml.org/self/2022/oct/07/sicherheitsleck-rechtschreibprufung-fur-passworte/1802518#m1802518) (German language).

**Comment by loesler** [comment]
Good work!
