### ISSUE TITLE
Which version of B8 do we run (2023-01-09)?

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#663]
@loesler While overworking the upgrade script I came across the pull requests about [upgrading](https://github.com/ilosuna/mylittleforum/pull/557) and [downgrading](https://github.com/ilosuna/mylittleforum/pull/561) B8 because of issues with the new version. The library itself provides no version information. When comparing the code of [the original b8.php (version 0.7)](https://gitlab.com/l3u/b8/-/blob/v0.7/b8/b8.php) with [the code we use in MLF version 20220803.1](https://github.com/ilosuna/mylittleforum/blob/20220803.1/modules/b8/b8.php), I see the first differences in `spl_autoload_register` ([original B8 version 0.7](https://gitlab.com/l3u/b8/-/blob/v0.7/b8/b8.php#L32) versus [mlf 20220803.1](https://github.com/ilosuna/mylittleforum/blob/20220803.1/modules/b8/b8.php#L32)). On the other hand our code differs much more from [the original code of the previous version 0.6.2](https://gitlab.com/l3u/b8/-/blob/v0.6.2/b8/b8.php).

So my question is: Which version of B8 do we run?

**Comment by loesler** [comment]
The latest version (v0.7), cf. #562

**Comment by auge8472** [comment]
Thank you for your commitment. So the additional code in `spl_autoload_register` *is* the difference.

**Comment by loesler** [comment]
Maybe, the [provided fix](https://gitlab.com/l3u/b8/-/merge_requests/1) is not part of the download package but it was committed.
