### ISSUE TITLE
store read status of entries in a table instead a column

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#72]
Addendum to #45 and #71, part of a detailed plan in several issues.

**Comment by derletztekick** [comment]
We can optimise this function by restrict the entries to the postings that are NOT written by the user itself. The entries, which are written by the user, are always marked as "read" (per default).

**Comment by auge8472** [comment]
> We can optimise this function by restrict the entries to the postings that are NOT written by the user him/herself. The entries, which are written by the user, are always marked as "read" (per default).

Can you please explain a bit more, what your point is?

**Comment by derletztekick** [comment]
The owner's postings are always marked as read (without explicit storing a flag in a db table). The owner always has read his/her posting because (s)he is the owner.

**Comment by auge8472** [comment]
> The owner's postings should always marked as read (without explicit storing a flag in a db table).

That's true, but it requires additional code (a check for the users own entry). I believe, it would codewise be cheaper to store the users own entries in the table. **And**, this is a more selfexplanatory code than it would be with the exceptional handling of the users own entries.

Therefore see also [this confusion](http://mylittleforum.net/forum/index.php?id=9648). :-)

**Comment by derletztekick** [comment]
> this is a more selfexplanatory code

Is this condition not self-explanatory: `$_SESSION[$settings['session_prefix'].'user_id'] == $data['user_id'] --> is_read = true?`

```
if (isset($_SESSION[$settings['session_prefix'].'user_id']) && $_SESSION[$settings['session_prefix'].'user_id'] == $data['user_id'] || $data['req_user'] !== NULL && is_numeric($data['req_user'])) {
    $data['is_read'] = true;
}
//...
```

and a small modification on the save_read_status() function.

**Comment by auge8472** [comment]
These lines of code in itself are selfexplanatory. But it is additional code and it is spread over *at least* two places instead the one additional join in every relevant database query.

I think, it is unnecessary code. The space for the additional datasets (two integers and one date) is IMHO cheaper than the code and it's additional complexity in the case of a change months or years later when nobody knows, what the meaning of the code was.

**Comment by derletztekick** [comment]
> instead the one additional join in every relevant database query.

Wowowow, you don't just add another join to sql statements, you also add some new lines of code e.g. [thread.inc.php#L262](https://github.com/ilosuna/mylittleforum/blob/master/includes/thread.inc.php#L262). So, my suggestion/modification will take place in the same area - that is contradictory. 

Anyway, we can also extend the sql statement ([thread.inc.php#L70](https://github.com/ilosuna/mylittleforum/blob/master/includes/thread.inc.php#L70)) by a new row `SELECT (IFNULL(rst.user_id, -1) = ft.user_id) AS is_posting_owner, id, pid, ....`

Now, the field `is_posting_owner` indicates the state (true/false).

**Comment by auge8472** [comment]
> Wowowow, you don't just add another join to sql statements, you also add some new lines of code e.g. thread.inc.php#L262.

That line would stay there with or without your idea. So what?

>  So, my suggestion/modification will take place in the same area - that is contradictory.

It would add code in that area or inside the query (with the subquery). Anyway, I don't want to fight with you, but …

… with storing every single entry that was read by any registered user in the read-status-table we have a functional simple solution. No confusion and much more important: no exception. To handle an entry/the entries of the logged-in user in a different way *will add compexity*, even it's _only **a little bit**_. Also it's *IMHO* a muddle if one of us want to change the code later. Like I stated a few posts before with the link "this confusion", we have actually a problem with incomprehensible code. I don't wish to add further code, that delivers a solution to a non existing problem and to make me or you think about the meaning of the code months or years later.

*Thatswhy* I argue against the additional code, that is IMHO not necessary.

**Comment by derletztekick** [comment]
> I argue against the additional code, that is IMHO not necessary.

I agree!
