### ISSUE TITLE
remove read status of entries when auto locking threads after time X or in general time dependent

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#75]
Addendum to #45, #71, #72, part of a detailed plan in several issues.

**Comment by derletztekick** [comment]
Do I understand this in the right manner: You want to remove the read-state, if the thread is locked by the auto-locking function of the forum?

**Comment by auge8472** [comment]
> You want to remove the read-state, if the thread is locked by the auto-locking function of the forum?

Yes, that's my idea. We discussed this task with @glorifyday (see #45) and it was in question, how many datasets should be stored per user. The possible solutions:

1. Store an unlimited amount of datasets. Table could become very big dependent from the typical users behaviour in a certain forum.
2. Store datasets for all entries and remove them ordered by the oldest requests as first.
3. Store datasets for all entries and remove them dependent from the auto-locking **if this feature is activated**.

Point 1 is the easiest. Take your fingers away and let happen what happens, Points 2 and 3 should IMHO be dependent from the installations settings. Is this comprehensible?

**Comment by derletztekick** [comment]
Done by https://github.com/ilosuna/mylittleforum/pull/82

**Comment by derletztekick** [comment]
Do we still need the item 'max_read_items' or should we include this setting to the delete routine?

**Comment by auge8472** [comment]
> Do we still need the item 'max_read_items' or should we include this setting to the delete routine?

That's a setting, isn't it? If yes, it is not necessary anymore.

**Comment by derletztekick** [comment]
>  I think, we should keep this setting for those admins, who wishes to limit the number of entries with read-status for every single user.

Okay, done by https://github.com/ilosuna/mylittleforum/pull/125
