### ISSUE TITLE
Transfer of read status from the userdata- to the read-status-table?

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#77]
Is it wo*r*th the effort to transfer the existing read markings when updating the forum script? After the update to version 2.4 the collection of read entries can be started from scratch with the new, empty table or with the existing collection in the userdata table. Make it easy for us or for the users of the MLF2-driven forums? Ha*ve* the existing collections a relevant importance?

**[edit]:** typos (*italic* letters)

**Comment by derletztekick** [comment]
> Has the existing collections a relevant importance?

It would be a nice to have if one transfers the old date to the new table.

**Comment by derletztekick** [comment]
Hi, I found this solution for mysql: [SQL split values to multiple rows](http://stackoverflow.com/questions/17942508/sql-split-values-to-multiple-rows). It seems to be work [fine](http://sqlfiddle.com/#!2/a213e4/1).

**Comment by auge8472** [comment]
It seems to be work fine (link inside).

The link in the word "fine" is broken. I get status 404.

**Comment by derletztekick** [comment]
The link points to a live-demo at http://sqlfiddle.com taken from the posting at http://stackoverflow.com

**Comment by auge8472** [comment]
Ok, no 404, **but** no functionallity without activation of JavaScript for google-analytics.com? ***Serious? NO WAY!***

**Comment by derletztekick** [comment]
I will try the code on my local installation and give feedback

**Comment by derletztekick** [comment]
Done by https://github.com/ilosuna/mylittleforum/pull/81
