### ISSUE TITLE
Setting doublettes, no index in the settings table

### ISSUE THREAD

**Issue by auge8472** [ilosuna/mylittleforum#99]
In case of an update or an bug (see #98) settings can be doubled. That leads to the problem, that the last occurence of an setting will be used, but the first (*not used*) will be altered with changes in the settings form.

I tend to create a primary index for the column "name", but when there are doublettes present, then this attempt will fail. It might be an idea for the update to …

- … read the settings table, …
- … store the settings in an array (as usual), …
- … remove all entries from the table, …
- … alter the table structure …
- … and restore the settings from the array.

**Comment by derletztekick** [comment]
We know the items in this table, so we can remove duplicate before adding the primary key condition

**Comment by derletztekick** [comment]
I don't like to discuss on several places about the same item. So, I don't understand why someone has a duplicate entry (and other one has not). I don't like to remove the table with 99 % valid entries.What do you think about a temporary rename of one value, i.e.:

```
UPDATE `mlf2_settings` SET `name`= 'auto_lock_old_threads_tmp' WHERE `name`= 'auto_lock_old_threads' LIMIT 1;
DELETE FROM `mlf2_settings` WHERE `name` = 'auto_lock_old_threads';
UPDATE `mlf2_settings` SET `name`= 'auto_lock_old_threads' WHERE `name`= 'auto_lock_old_threads_tmp' LIMIT 1;
```

**Comment by auge8472** [comment]
That's a nice and simple idea for this one setting. But before you begin to alter the code, I want to describe cases, when doublettes of *not only one setting* can occure. I will do this **tomorrow**, because writing on the phone is a bit complicated and I have today no access to a computer with a qualified keyboard.

**Comment by derletztekick** [comment]
I'll wait....

**Comment by auge8472** [comment]
After two hours of serching [I found the thread](http://mylittleforum.net/forum/index.php?id=5326), where I faced the problem for the first time. The OP had several problems, one was, that she was unable to save changes to the settings. I had a public and a private conversation over e-mail with the OP and it turns out, that she (or a helping hand) undertook a new installation of the forum with a following backup of the data from the last installation.

The consequence was a full doubled set of settings. That's only one (*my* first) case. Last one was my mistake, to [use testing code](https://github.com/ilosuna/mylittleforum/pull/94/commits/55e56deba22423b34d5db79e922e3d3c5453c31e) (see #94 ) with wrong table names, that leads to a wrong version string in one of my test installations and [the doubled setting](https://github.com/ilosuna/mylittleforum/pull/100/commits/f223f0071352f50e06b303b988bab91976008a91) `auto_lock_old_threads` (see #100).

*Maybe* [this](http://mylittleforum.net/forum/index.php?id=4943) and [that](http://mylittleforum.net/forum/index.php?id=5903) was further occurences of the same problem. But that's a speculation from my side.

**Comment by derletztekick** [comment]
Okay. I support your suggestion to add a primary key in this table to avoid this behaviour but I don't understand how my local installation could be affected ....

**Comment by auge8472** [comment]
> I don't understand how my local installation could be affected

If one do not undertake crappy experiments and make no mistakes while installing and updating and do not introduce errors into the code, ones local installation will never be affected (whoever "one" will be). :-)

This is only an attempt to reduce the errors in corner cases.

**Comment by derletztekick** [comment]
I add my sql code and the primary key condition to the update script. Please merge https://github.com/ilosuna/mylittleforum/pull/112, if it is okay for you
